const {app,BrowserWindow}=require('electron');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
app.disableHardwareAcceleration();
app.whenReady().then(async()=>{let win;try{
 const errors=[];win=new BrowserWindow({width:1460,height:1040,show:false,webPreferences:{offscreen:true,preload:path.join(__dirname,'ui-preload.cjs'),contextIsolation:true,sandbox:true}});win.webContents.on('console-message',(_e,level,message)=>{if(level===3)errors.push(message);});
 await win.loadFile(path.join(__dirname,'../renderer/index.html'));const evaluate=code=>win.webContents.executeJavaScript(code,true);await new Promise(r=>setTimeout(r,500));
 assert.equal(await evaluate('document.querySelectorAll(".effect").length'),8);assert.equal(await evaluate('document.getElementById("audioDialog").open'),false);assert.equal(await evaluate('document.querySelectorAll(".effect [data-toggle]").length'),8);
 await evaluate('document.querySelector("[data-open=audioDialog]").click()');assert.equal(await evaluate('document.getElementById("audioDialog").open'),true);await evaluate('document.getElementById("apply").click()');await new Promise(r=>setTimeout(r,100));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='configure'&&c.data.micChannel===0&&c.data.musicLeft===2));
 fs.mkdirSync('build/ui',{recursive:true});async function shot(name){await new Promise(r=>setTimeout(r,120));fs.writeFileSync(`build/ui/${name}.png`,(await win.webContents.capturePage()).toPNG());}
 await shot('audio-settings');await evaluate('document.getElementById("audioDialog").close();document.getElementById("live").click()');await new Promise(r=>setTimeout(r,100));
 // Every built-in slider must produce an actual native parameter command.
 const ids=await evaluate('Array.from(document.querySelectorAll("[data-param]")).map(x=>x.dataset.param)');for(const id of ids.filter(x=>x!=='autoAmount')){await evaluate(`(()=>{const x=document.querySelector('[data-param="${id}"]');x.value=String(Number(x.min)+(Number(x.max)-Number(x.min))*.6);x.dispatchEvent(new Event('change',{bubbles:true}));})()`);await new Promise(r=>setTimeout(r,40));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='params'&&Object.hasOwn(c.data,id)),`No audio command for ${id}`);}
 await evaluate('document.querySelector("#fx-tune [data-toggle]").click()');await new Promise(r=>setTimeout(r,50));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='params'&&c.data.tune===true));
 await evaluate('document.querySelector("[data-listen=music]").click()');await new Promise(r=>setTimeout(r,50));assert((await evaluate('window.testBridge.changes()')).some(c=>c.data.listenMode==='music'));
 await evaluate('document.querySelector("[data-open=autoDialog]").click();document.getElementById("autoStart").click()');await new Promise(r=>setTimeout(r,50));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='auto-vocal'));await evaluate('window.testBridge.emit({event:"auto-complete",settings:{autoProfile:{},autoAmount:.7},message:"MIC analysis complete"})');await shot('auto-vocal');
 await evaluate('document.getElementById("autoDialog").close();document.querySelector("[data-open=tuneDialog]").click()');await shot('autotune');await evaluate('document.getElementById("tuneDialog").close()');
 await evaluate('window.testBridge.emit({event:"meters",mic:.3,music:.2,master:.4,live:true,recording:false,autoRunning:false,autoProgress:1,pitchHz:450,targetHz:440,pitchConfidence:.99,detectedKey:0,waveform:Array.from({length:128},(_,i)=>Math.sin(i*.16)*.35),micWave:Array.from({length:128},(_,i)=>Math.sin(i*.25)*.18),musicWave:Array.from({length:128},(_,i)=>Math.cos(i*.11)*.2)})');await shot('studio');
 await evaluate('document.querySelector("[data-open=settingsDialog]").click();document.getElementById("language").value="en";document.getElementById("applyLanguage").click()');await new Promise(r=>setTimeout(r,120));assert.equal(await evaluate('document.documentElement.lang'),'en');assert.equal(await evaluate('localStorage.getItem("hnstudio.language")'),'en');assert.equal(await evaluate('document.querySelector("[data-open=settingsDialog]").textContent'),'SETTINGS');await shot('language-settings');
 await evaluate('document.getElementById("language").value="vi";document.getElementById("applyLanguage").click()');await new Promise(r=>setTimeout(r,120));assert.equal(await evaluate('document.querySelector("[data-open=settingsDialog]").textContent'),'CÀI ĐẶT');await evaluate('document.getElementById("settingsDialog").close();document.querySelector("[data-open=tuneDialog]").click();document.getElementById("redetectKey").click()');await new Promise(r=>setTimeout(r,80));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='key-reset'));await evaluate('window.testBridge.emit({event:"meters",mic:.3,music:.2,master:.4,autoRunning:false,keyReady:true,detectedKey:7,keyConfidence:.9,eqLevels:Array(13).fill(.1)})');await new Promise(r=>setTimeout(r,80));assert.equal(await evaluate('document.getElementById("key").value'),'G');assert.equal(await evaluate('document.getElementById("key").disabled'),true);assert.equal(await evaluate('document.getElementById("tuneMode").selectedOptions[0].textContent'),'Theo key / scale');assert.equal(await evaluate('getComputedStyle(document.querySelector("dialog")).backdropFilter'),'none');await shot('autokey-live');
 await evaluate('document.getElementById("tuneDialog").close();document.querySelector("[data-open=eqDialog]").click()');await shot('eq-neon');await evaluate('document.getElementById("eqDialog").close();document.querySelector("[data-open=aboutDialog]").click()');assert((await evaluate('document.getElementById("aboutDialog").textContent')).includes('0965.043.000'));assert((await evaluate('document.getElementById("aboutDialog").textContent')).includes('Tool được tạo bởi Hoài Nguyễn Studio.'));await shot('about');assert.equal(errors.length,0,errors.join('\n'));
 await evaluate('document.getElementById("aboutDialog").close();document.getElementById("recordWorkspace").click()');await new Promise(r=>setTimeout(r,100));assert.equal(await evaluate('document.getElementById("recordDesk").hidden'),false);assert.equal(await evaluate('document.querySelectorAll(".track-row").length'),4);await shot('recording-desk');await evaluate('document.getElementById("dawPlay").click()');await new Promise(r=>setTimeout(r,100));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='timeline'&&c.data.action==='play'));await evaluate('document.getElementById("dawStop").click()');await new Promise(r=>setTimeout(r,100));await evaluate('document.getElementById("armedTrack").value="2";document.getElementById("dawRecord").click()');await new Promise(r=>setTimeout(r,100));assert((await evaluate('window.testBridge.changes()')).some(c=>c.op==='timeline'&&c.data.action==='record'&&c.data.track===2));await evaluate('document.getElementById("dawStop").click()');await new Promise(r=>setTimeout(r,100));await evaluate('document.querySelectorAll(".track-buttons button")[5].click()');await new Promise(r=>setTimeout(r,100));assert.equal(await evaluate('document.getElementById("trackFxDialog").open'),true);assert.equal(await evaluate('document.querySelectorAll(".track-insert").length'),4);await shot('track-fx');assert.equal(errors.length,0,errors.join('\n'));
 console.log('UI smoke passed: popup dialogs, all built-in faders send audio params, AutoTune ON/OFF, source isolation and Auto Vocal command. Captured 4 previews.');win.destroy();app.exit(0);
 }catch(e){console.error(e);win?.destroy();app.exit(1);}});
