const {app,BrowserWindow,ipcMain,dialog,shell}=require('electron');
const {spawn}=require('node:child_process');
const fs=require('node:fs/promises');const path=require('node:path');const readline=require('node:readline');
let uiLanguage='vi';const tr=(vi,en)=>uiLanguage==='en'?en:vi;
let window,backend,sequence=0,closing=false;const pending=new Map();const log=[];
function event(value){if(value.event==='error')log.push(`${new Date().toISOString()} ${value.message}`);if(window&&!window.isDestroyed())window.webContents.send('audio:event',value);}
function boot(){const exe=app.isPackaged?path.join(process.resourcesPath,'native','hn-audio.exe'):path.join(__dirname,'../build/native/Release/hn-audio.exe');backend=spawn(exe,[],{windowsHide:true,stdio:['pipe','pipe','pipe']});backend.on('error',e=>event({event:'error',message:`Cannot start native audio: ${e.message}`}));backend.stdin.on('error',e=>event({event:'error',message:e.message}));readline.createInterface({input:backend.stdout}).on('line',line=>{try{const value=JSON.parse(line);if(value.id&&pending.has(value.id)){const p=pending.get(value.id);clearTimeout(p.timer);pending.delete(value.id);if(value.ok)p.resolve(value.data);else{log.push(`${new Date().toISOString()} ${value.error}`);p.reject(new Error(value.error));}}else event(value);}catch{event({event:'error',message:`Invalid backend response: ${line.slice(0,200)}`});}});backend.stderr.on('data',data=>event({event:'error',message:data.toString()}));backend.on('exit',(code,signal)=>{backend=null;for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error(`Audio backend stopped (${code??signal})`));}pending.clear();if(!closing)event({event:'error',message:`Audio backend stopped (${code??signal}); restart app.`});});}
function request(op,data={}){return new Promise((resolve,reject)=>{if(!backend||!backend.stdin.writable)return reject(new Error('Native audio is unavailable'));const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`${op} timed out; see audio log`));},op==='timeline'?300000:60000);pending.set(id,{resolve,reject,timer});backend.stdin.write(JSON.stringify({id,op,data})+'\n');});}
const asioDownloadUrl='https://drive.usercontent.google.com/download?id=13NA49N9QOwn9F79Q8wlgK2Tz_QtsthoC&export=download&authuser=0';
ipcMain.handle('ui:asio-download',async e=>{if(e.sender!==window.webContents)throw new Error('Invalid sender');await shell.openExternal(asioDownloadUrl);});
const allowed=new Set(['devices','ports','control-panel','auto-vocal','auto-amount','key-reset','configure','params','live','test','soundboard']);
ipcMain.handle('ui:language',(e,language)=>{if(e.sender!==window.webContents||!['vi','en'].includes(language))throw new Error('Invalid UI language');uiLanguage=language;return {language};});
ipcMain.handle('audio:command',async(e,op,data)=>{if(e.sender!==window.webContents||!allowed.has(op))throw new Error('Invalid command');return request(op,data);});
ipcMain.handle('audio:slot',async(e,index,action,value)=>{if(!Number.isInteger(index)||index<0||index>3)throw new Error('Invalid slot');if(action==='load'){const result=await dialog.showOpenDialog(window,{title:tr('Chọn plugin VST3','Select VST3 module'),properties:['openFile','openDirectory'],filters:[{name:'VST3',extensions:['vst3']}]});if(result.canceled)return null;return request('slot',{index,action,path:result.filePaths[0]});}if(action==='installed'){const list=await scanTrackPlugins();if(!value||!list.some(p=>p.path===value.path))throw new Error('VST3 is not in the installed plugin list');return request('slot',{index,action:'load',path:value.path});}if(!['remove','on','bypass','parameter'].includes(action))throw new Error('Invalid slot action');return request('slot',{index,action,...(action==='parameter'?value:{value})});});
ipcMain.handle('audio:record',async(e,on)=>{if(!on)return request('record',{on:false});const result=await dialog.showSaveDialog(window,{title:tr('Ghi âm thanh tổng WAV 24-bit','Record Master WAV 24-bit'),defaultPath:`HNStudio-${Date.now()}.wav`,filters:[{name:'WAV',extensions:['wav']}]});if(result.canceled)return null;try{await fs.access(result.filePath);await fs.unlink(result.filePath);}catch(e){if(e.code!=='ENOENT')throw e;}return request('record',{on:true,path:result.filePath});});
ipcMain.handle('audio:project',async(e,action)=>{if(action==='save'){const result=await dialog.showSaveDialog(window,{defaultPath:'HNStudio-project.hnproj',filters:[{name:tr('Dự án HNStudio','HNStudio project'),extensions:['hnproj']}]});if(result.canceled)return null;const project=await request('project-save');await fs.writeFile(result.filePath,JSON.stringify(project,null,2),'utf8');return project;}if(action==='load'){const result=await dialog.showOpenDialog(window,{filters:[{name:tr('Dự án HNStudio','HNStudio project'),extensions:['hnproj']}],properties:['openFile']});if(result.canceled)return null;const stat=await fs.stat(result.filePaths[0]);if(stat.size>32*1024*1024)throw new Error('Project exceeds 32 MB');return request('project-load',JSON.parse(await fs.readFile(result.filePaths[0],'utf8')));}throw new Error('Invalid project action');});
ipcMain.handle('audio:log',async()=>{const result=await dialog.showSaveDialog(window,{defaultPath:'HNStudio-audio.log'});if(!result.canceled)await fs.writeFile(result.filePath,log.join('\n'),'utf8');});
ipcMain.handle('audio:sound-load',async(e,pad)=>{if(e.sender!==window.webContents||!Number.isInteger(pad)||pad<0||pad>5)throw new Error('Invalid pad');const r=await dialog.showOpenDialog(window,{title:tr('Nạp âm thanh LIVE','Load LIVE sound'),properties:['openFile'],filters:[{name:'Audio',extensions:['wav','mp3','flac','aif','aiff']}]});if(r.canceled)return null;return request('soundboard',{action:'load',pad,path:r.filePaths[0]});});
let takeDirectory;
async function scanTrackPlugins(){const roots=[path.join(process.env.CommonProgramFiles||'C:\\Program Files\\Common Files','VST3'),path.join(process.env.LOCALAPPDATA||app.getPath('userData'),'Programs','Common','VST3')];const list=[];async function visit(dir,depth){if(depth>4||list.length>=400)return;let entries;try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){const p=path.join(dir,e.name);if(/\.vst3$/i.test(e.name))list.push({name:e.name,path:p});else if(e.isDirectory())await visit(p,depth+1);}}for(const root of roots)await visit(root,0);return list;}
ipcMain.handle('audio:timeline',async(e,data={})=>{if(e.sender!==window.webContents)throw new Error('Invalid sender');const c={...data};
 if(c.action==='plugins')return {plugins:await scanTrackPlugins()};
 if(c.action==='load'){const r=await dialog.showOpenDialog(window,{title:tr('Nạp beat / audio vào track','Import beat / audio into track'),properties:['openFile'],filters:[{name:'Audio',extensions:['wav','mp3','flac','aif','aiff']}]});if(r.canceled)return null;c.path=r.filePaths[0];}
 if(c.action==='record'){takeDirectory=takeDirectory||path.join(app.getPath('documents'),'HNStudio Takes');await fs.mkdir(takeDirectory,{recursive:true});c.path=path.join(takeDirectory,`Mic-${c.track}-${Date.now()}.wav`);}
 if(c.action==='insert'&&c.operation==='load'&&!c.path){const r=await dialog.showOpenDialog(window,{title:tr('Nạp VST3 cho track','Load track VST3'),properties:['openFile','openDirectory'],filters:[{name:'VST3',extensions:['vst3']}]});if(r.canceled)return null;c.path=r.filePaths[0];}
 if(c.action==='export'){const r=await dialog.showSaveDialog(window,{title:tr('Xuất bản thu WAV 24-bit','Export recording WAV 24-bit'),defaultPath:'HNStudio-Mix.wav',filters:[{name:'WAV',extensions:['wav']}]});if(r.canceled)return null;await fs.rm(r.filePath,{force:true});c.path=r.filePath;}
 if(c.action==='save'){const r=await dialog.showSaveDialog(window,{title:tr('Lưu dự án thu âm','Save recording project'),defaultPath:'HNStudio-Recording.hnrec',filters:[{name:'HNStudio Recording',extensions:['hnrec']}]});if(r.canceled)return null;const project=await request('timeline',{action:'save'});const media=r.filePath+'.media';await fs.mkdir(media,{recursive:true});const copies=new Map();for(const t of project.tracks)for(const clip of t.clips||[]){if(!clip.path)continue;let dest=copies.get(clip.path);if(!dest){dest=path.join(media,`${t.index}-${clip.id}-${path.basename(clip.path)}`);if(path.resolve(clip.path)!==path.resolve(dest))await fs.copyFile(clip.path,dest);copies.set(clip.path,dest);}clip.path=dest;}await fs.writeFile(r.filePath,JSON.stringify(project,null,2),'utf8');return {saved:r.filePath};}
 if(c.action==='restore'){const r=await dialog.showOpenDialog(window,{title:tr('Mở dự án thu âm','Open recording project'),properties:['openFile'],filters:[{name:'HNStudio Recording',extensions:['hnrec']}]});if(r.canceled)return null;const stat=await fs.stat(r.filePaths[0]);if(stat.size>32*1024*1024)throw new Error('Project exceeds 32 MB');c.project=JSON.parse(await fs.readFile(r.filePaths[0],'utf8'));}
 if(!['state','load','edit','remove','move','split','seek','play','stop','record','export','restore','insert'].includes(c.action))throw new Error('Invalid timeline action');return request('timeline',c);
});

app.whenReady().then(()=>{window=new BrowserWindow({width:1440,height:960,minWidth:1000,minHeight:740,backgroundColor:'#080b14',title:'HNStudio Musik AI',icon:path.join(__dirname,'../renderer/assets/icon.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.loadFile(path.join(__dirname,'../renderer/index.html'));window.webContents.once('did-finish-load',boot);});
app.on('window-all-closed',()=>app.quit());
app.on('before-quit',e=>{if(closing)return;if(backend){e.preventDefault();closing=true;const child=backend;child.once('exit',()=>app.quit());child.stdin.end(JSON.stringify({op:'quit'})+'\n');setTimeout(()=>{child.kill();app.quit();},3000).unref();}});
