const {app,BrowserWindow,ipcMain,dialog}=require('electron');
const {spawn}=require('node:child_process');
const fs=require('node:fs/promises');const path=require('node:path');const readline=require('node:readline');
let window,backend,sequence=0,closing=false;const pending=new Map();const log=[];
function event(value){if(value.event==='error')log.push(`${new Date().toISOString()} ${value.message}`);if(window&&!window.isDestroyed())window.webContents.send('audio:event',value);}
function boot(){const exe=app.isPackaged?path.join(process.resourcesPath,'native','hn-audio.exe'):path.join(__dirname,'../build/native/Release/hn-audio.exe');backend=spawn(exe,[],{windowsHide:true,stdio:['pipe','pipe','pipe']});backend.on('error',e=>event({event:'error',message:`Cannot start native audio: ${e.message}`}));backend.stdin.on('error',e=>event({event:'error',message:e.message}));readline.createInterface({input:backend.stdout}).on('line',line=>{try{const value=JSON.parse(line);if(value.id&&pending.has(value.id)){const p=pending.get(value.id);clearTimeout(p.timer);pending.delete(value.id);if(value.ok)p.resolve(value.data);else{log.push(`${new Date().toISOString()} ${value.error}`);p.reject(new Error(value.error));}}else event(value);}catch{event({event:'error',message:`Invalid backend response: ${line.slice(0,200)}`});}});backend.stderr.on('data',data=>event({event:'error',message:data.toString()}));backend.on('exit',(code,signal)=>{backend=null;for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error(`Audio backend stopped (${code??signal})`));}pending.clear();if(!closing)event({event:'error',message:`Audio backend stopped (${code??signal}); restart app.`});});}
function request(op,data={}){return new Promise((resolve,reject)=>{if(!backend||!backend.stdin.writable)return reject(new Error('Native audio is unavailable'));const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`${op} timed out; see audio log`));},60000);pending.set(id,{resolve,reject,timer});backend.stdin.write(JSON.stringify({id,op,data})+'\n');});}
const allowed=new Set(['devices','ports','control-panel','configure','params','live','test']);
ipcMain.handle('audio:command',async(e,op,data)=>{if(e.sender!==window.webContents||!allowed.has(op))throw new Error('Invalid command');return request(op,data);});
ipcMain.handle('audio:slot',async(e,index,action,value)=>{if(!Number.isInteger(index)||index<0||index>3)throw new Error('Invalid slot');if(action==='load'){const result=await dialog.showOpenDialog(window,{title:'Select VST3 module',properties:['openFile','openDirectory'],filters:[{name:'VST3',extensions:['vst3']}]});if(result.canceled)return null;return request('slot',{index,action,path:result.filePaths[0]});}if(!['remove','on','bypass','parameter'].includes(action))throw new Error('Invalid slot action');return request('slot',{index,action,...(action==='parameter'?value:{value})});});
ipcMain.handle('audio:record',async(e,on)=>{if(!on)return request('record',{on:false});const result=await dialog.showSaveDialog(window,{title:'Record Master WAV 24-bit',defaultPath:`HNStudio-${Date.now()}.wav`,filters:[{name:'WAV',extensions:['wav']}]});if(result.canceled)return null;try{await fs.access(result.filePath);await fs.unlink(result.filePath);}catch(e){if(e.code!=='ENOENT')throw e;}return request('record',{on:true,path:result.filePath});});
ipcMain.handle('audio:project',async(e,action)=>{if(action==='save'){const result=await dialog.showSaveDialog(window,{defaultPath:'HNStudio-project.hnproj',filters:[{name:'HNStudio project',extensions:['hnproj']}]});if(result.canceled)return null;const project=await request('project-save');await fs.writeFile(result.filePath,JSON.stringify(project,null,2),'utf8');return project;}if(action==='load'){const result=await dialog.showOpenDialog(window,{filters:[{name:'HNStudio project',extensions:['hnproj']}],properties:['openFile']});if(result.canceled)return null;const stat=await fs.stat(result.filePaths[0]);if(stat.size>32*1024*1024)throw new Error('Project exceeds 32 MB');return request('project-load',JSON.parse(await fs.readFile(result.filePaths[0],'utf8')));}throw new Error('Invalid project action');});
ipcMain.handle('audio:log',async()=>{const result=await dialog.showSaveDialog(window,{defaultPath:'HNStudio-audio.log'});if(!result.canceled)await fs.writeFile(result.filePath,log.join('\n'),'utf8');});
app.whenReady().then(()=>{window=new BrowserWindow({width:1440,height:960,minWidth:1000,minHeight:740,backgroundColor:'#080b14',title:'HNStudio Musik AI',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.loadFile(path.join(__dirname,'../renderer/index.html'));window.webContents.once('did-finish-load',boot);});
app.on('window-all-closed',()=>app.quit());
app.on('before-quit',e=>{if(closing)return;if(backend){e.preventDefault();closing=true;const child=backend;child.once('exit',()=>app.quit());child.stdin.end(JSON.stringify({op:'quit'})+'\n');setTimeout(()=>{child.kill();app.quit();},3000).unref();}});
