#pragma once
#include <juce_audio_utils/juce_audio_utils.h>
#include <nlohmann/json.hpp>
// Original synthesized stingers; custom samples are decoded off the audio thread.
class Soundboard {
 std::array<juce::AudioBuffer<float>,6> samples;std::array<double,6> sampleRates{};std::array<bool,6> custom{};std::array<std::string,6> names{"Cười vui · tổng hợp","Vỗ tay","Boing hài","Ting","Trống vui","Còi vui"};
 struct Voice{int pad=-1;double frame=0;};std::array<Voice,12> voices;std::array<std::atomic<unsigned>,6> triggers{};std::array<unsigned,6> consumed{};juce::AudioFormatManager readers;double rate=48000;unsigned randomState=1234567;
 float noise(){randomState=randomState*1664525u+1013904223u;return float((randomState>>8)/8388608.)-1.f;}
public:
 float volume=.5f;juce::AudioBuffer<float> mix;
 Soundboard(){readers.registerBasicFormats();prepare(48000,512);}
 void prepare(double sr,int block){rate=sr;mix.setSize(2,std::max(8192,block));stop();for(int pad=0;pad<6;++pad){if(custom[pad])continue;double length=pad==0?2.4:pad==1?3.0:pad==2?1.1:pad==3?.8:pad==4?1.8:1.2;samples[pad].setSize(2,int(rate*length));sampleRates[pad]=rate;double phase=0;for(int i=0;i<samples[pad].getNumSamples();++i){double t=i/rate;float value=0;if(pad==0){double syllable=std::fmod(t,.30);double envelope=syllable<.19?std::sin(juce::MathConstants<double>::pi*syllable/.19):0;double hz=165+24*std::sin(t*9);phase+=2*juce::MathConstants<double>::pi*hz/rate;value=float(envelope*.22*(std::sin(phase)+.4*std::sin(phase*3)+.2*std::sin(phase*5))*(1-t/length));}else if(pad==1){double pulse=std::fmod(t,.085);value=noise()*float(.4*std::exp(-pulse*95)*(1-t/length));}else if(pad==2){phase+=2*juce::MathConstants<double>::pi*(75+450*std::exp(-t*5)*(1+.35*std::sin(t*65)))/rate;value=float(.4*std::sin(phase)*std::exp(-t*4));}else if(pad==3)value=float(.3*(std::sin(t*2*juce::MathConstants<double>::pi*1046)+.3*std::sin(t*2*juce::MathConstants<double>::pi*2092))*std::exp(-t*7));else if(pad==4){double pulse=std::fmod(t,.055);value=noise()*float(.3*std::exp(-pulse*100)*(t/length));}else value=float(.23*(std::sin(t*2*juce::MathConstants<double>::pi*440)+.4*std::sin(t*2*juce::MathConstants<double>::pi*660))*std::min(1.,t*30)*(1-t/length));for(int ch=0;ch<2;++ch)samples[pad].setSample(ch,i,value);}}}
 void stop(){for(auto& v:voices)v=Voice{};for(int i=0;i<6;++i)consumed[i]=triggers[i].load();}
 void trigger(int pad){if(pad<0||pad>=6)throw std::runtime_error("Sound pad không hợp lệ");++triggers[pad];}
 void load(int pad,const std::string& path){if(pad<0||pad>=6)throw std::runtime_error("Sound pad không hợp lệ");std::unique_ptr<juce::AudioFormatReader> r(readers.createReaderFor(juce::File(path)));if(!r||r->lengthInSamples<=0||r->lengthInSamples>r->sampleRate*30||r->lengthInSamples>3000000)throw std::runtime_error("Âm thanh LIVE cần WAV/MP3/FLAC/AIFF tối đa 30 giây");juce::AudioBuffer<float> b(2,int(r->lengthInSamples));if(!r->read(&b,0,b.getNumSamples(),0,true,true))throw std::runtime_error("Không đọc được âm thanh LIVE");stop();samples[pad]=std::move(b);sampleRates[pad]=r->sampleRate;custom[pad]=true;names[pad]=juce::File(path).getFileNameWithoutExtension().toStdString();}
 nlohmann::json info(){return {{"names",names},{"volume",volume}};}
 void render(int n){mix.clear();for(int pad=0;pad<6;++pad){auto count=triggers[pad].load();if(count!=consumed[pad]){consumed[pad]=count;auto it=std::find_if(voices.begin(),voices.end(),[](auto& v){return v.pad<0;});if(it==voices.end())it=voices.begin();*it={pad,0};}}for(auto& v:voices){if(v.pad<0)continue;const auto& b=samples[v.pad];const double step=sampleRates[v.pad]/rate;for(int i=0;i<n;++i){if(v.frame>=b.getNumSamples()){v.pad=-1;break;}int a=int(v.frame),next=std::min(a+1,b.getNumSamples()-1);float f=float(v.frame-a);for(int ch=0;ch<2;++ch)mix.addSample(ch,i,(b.getSample(ch,a)*(1-f)+b.getSample(ch,next)*f)*volume);v.frame+=step;}}}
};
