#pragma once
#include <juce_audio_utils/juce_audio_utils.h>
#include <nlohmann/json.hpp>
#include "dsp.h"
#include <map>
#include <memory>
using TimelineJson=nlohmann::json;
// All edits/file IO run with the device callback detached. Only render() runs on audio thread.
class Timeline {
public:
 struct Insert {std::unique_ptr<juce::AudioPluginInstance> plugin;std::string path;bool on=true,bypass=false;};
 struct Source {juce::AudioBuffer<float> audio;double rate=48000;std::string path;std::array<float,800> wave{};};
 struct Clip {int id=0;std::shared_ptr<Source> source;double start=0,trimIn=0,trimOut=0;};
 struct Track {juce::AudioBuffer<float> work;std::vector<Clip> clips;float gain=1,pan=0;bool mute=false,solo=false;TimelineJson fx;VocalDSP dsp;std::array<Insert,4> inserts;std::atomic<float> peak{0};};
 std::array<Track,4> tracks;juce::AudioBuffer<float> mix,capture;juce::MidiBuffer midi;
 std::atomic<bool> playing{false},recording{false};std::atomic<double> position{0};std::atomic<unsigned> drops{0};
 int nextClipId=1;std::map<std::string,std::weak_ptr<Source>> cache;int armed=1;double rate=48000,recordStart=0,recordLatency=0;int block=512;std::string recordPath;std::unique_ptr<juce::AudioFormatWriter::ThreadedWriter> writer;juce::TimeSliceThread& disk;juce::AudioPluginFormatManager& formats;juce::AudioFormatManager readers;
 explicit Timeline(juce::TimeSliceThread& d,juce::AudioPluginFormatManager& f):disk(d),formats(f){readers.registerBasicFormats();for(auto& t:tracks)t.fx={{"enabled",false},{"gate",false},{"compressor",false},{"eq",false},{"deesser",false},{"tune",false},{"reverb",false},{"autoKey",true},{"key",0},{"minor",false},{"gateDb",-50},{"compressorDb",-18},{"ratio",3},{"essAmount",.5},{"reverbWet",.18},{"tuneStrength",.8},{"tuneSpeed",35},{"eqGains",std::vector<float>(13,0)}};prepare(rate,block);}
 void applyFx(Track& t){auto& f=t.fx;t.dsp.gate=f.value("gate",false);t.dsp.compressor=f.value("compressor",false);t.dsp.equalizer=f.value("eq",false);t.dsp.deesser=f.value("deesser",false);t.dsp.tune=f.value("tune",false);t.dsp.reverb=f.value("reverb",false);t.dsp.autoKey=f.value("autoKey",true);t.dsp.key=f.value("key",0);t.dsp.minor=f.value("minor",false);t.dsp.gateDb=f.value("gateDb",-50.f);t.dsp.threshold=f.value("compressorDb",-18.f);t.dsp.ratio=f.value("ratio",3.f);t.dsp.essAmount=f.value("essAmount",.5f);t.dsp.wet=f.value("reverbWet",.18f);t.dsp.tuneStrength=f.value("tuneStrength",.8f);t.dsp.tuneSpeed=f.value("tuneSpeed",35.f);auto gains=f.value("eqGains",std::vector<float>(13,0));for(int i=0;i<13;++i)t.dsp.eq[i].peak(rate,VocalDSP::hz[i],gains.at(i));}
 void prepare(double sr,int bs){rate=sr;block=bs;mix.setSize(2,std::max(8192,bs));capture.setSize(1,std::max(8192,bs));for(auto& t:tracks){t.work.setSize(2,std::max(8192,bs));t.dsp.prepare(rate);applyFx(t);for(auto& s:t.inserts)if(s.plugin){s.plugin->releaseResources();s.plugin->setRateAndBufferSizeDetails(rate,block);s.plugin->prepareToPlay(rate,block);}}}
 double clipDuration(const Clip& c)const{return std::max(0.,c.source->audio.getNumSamples()/c.source->rate-c.trimIn-c.trimOut);}
 double duration()const{double result=0;for(auto& t:tracks)for(auto& c:t.clips)result=std::max(result,c.start+clipDuration(c));return result;}
 Clip& getClip(int track,int id){auto& clips=tracks.at(track).clips;auto it=std::find_if(clips.begin(),clips.end(),[&](const Clip& c){return c.id==id;});if(it==clips.end())throw std::runtime_error("Không tìm thấy clip");return *it;}
 void validateClip(const Clip& c){if(!std::isfinite(c.start)||!std::isfinite(c.trimIn)||!std::isfinite(c.trimOut)||c.start<0||c.start>1800||c.trimIn<0||c.trimOut<0||c.trimIn+c.trimOut>c.source->audio.getNumSamples()/c.source->rate)throw std::runtime_error("Vị trí/cắt clip không hợp lệ");}
 void editClip(int track,int id,const TimelineJson& data){auto next=getClip(track,id);next.start=data.value("start",next.start);next.trimIn=data.value("trimIn",next.trimIn);next.trimOut=data.value("trimOut",next.trimOut);validateClip(next);getClip(track,id)=next;}
 void removeClip(int track,int id){auto& clips=tracks.at(track).clips;if(id<0){clips.clear();return;}getClip(track,id);std::erase_if(clips,[&](const Clip& c){return c.id==id;});}
 void moveClip(int from,int id,int to,double start){if(to<0||to>=4)throw std::runtime_error("Track đích không hợp lệ");auto c=getClip(from,id);c.start=start;validateClip(c);if(from==to){getClip(from,id)=c;return;}if(tracks[to].clips.size()>=64)throw std::runtime_error("Mỗi track tối đa 64 clip");tracks[to].clips.push_back(c);removeClip(from,id);}
 void splitClip(int track,int id,double at){auto original=getClip(track,id);const double offset=at-original.start;if(offset<=1/rate||offset>=clipDuration(original)-1/rate)throw std::runtime_error("Đặt con trỏ ở bên trong clip để cắt");auto& clips=tracks.at(track).clips;if(clips.size()>=64)throw std::runtime_error("Mỗi track tối đa 64 clip");auto left=original,right=original;left.trimOut=original.source->audio.getNumSamples()/original.source->rate-original.trimIn-offset;right.id=nextClipId++;right.start=at;right.trimIn=original.trimIn+offset;getClip(track,id)=left;clips.push_back(right);}
 void resetEffects(){for(auto& t:tracks){t.dsp.prepare(rate);applyFx(t);for(auto& s:t.inserts)if(s.plugin)s.plugin->reset();}}
 void requireStopped(){if(playing||recording)throw std::runtime_error("Dừng timeline trước khi chỉnh clip, nạp file hoặc VST");}
 std::shared_ptr<Source> readSource(const std::string& path){if(auto it=cache.find(path);it!=cache.end())if(auto source=it->second.lock())return source;std::unique_ptr<juce::AudioFormatReader> reader(readers.createReaderFor(juce::File(path)));if(!reader)throw std::runtime_error("Không đọc được WAV/MP3/FLAC/AIFF: "+path);if(reader->lengthInSamples<=0||reader->lengthInSamples>int64_t(reader->sampleRate*1800)||reader->lengthInSamples>32000000)throw std::runtime_error("File quá dài: tối đa 30 phút / 32 triệu mẫu");int64_t total=reader->lengthInSamples;for(auto it=cache.begin();it!=cache.end();){if(auto source=it->second.lock()){total+=source->audio.getNumSamples();++it;}else it=cache.erase(it);}if(total>64000000)throw std::runtime_error("Audio vượt giới hạn bộ nhớ 512 MB");auto source=std::make_shared<Source>();source->audio.setSize(2,int(reader->lengthInSamples));if(!reader->read(&source->audio,0,source->audio.getNumSamples(),0,true,true))throw std::runtime_error("Không đọc đủ dữ liệu audio");source->rate=reader->sampleRate;source->path=path;const int count=source->audio.getNumSamples();for(int bin=0;bin<800;++bin){float peak=0;for(int n=int(int64_t(bin)*count/800);n<int(int64_t(bin+1)*count/800);++n)for(int ch=0;ch<2;++ch)peak=std::max(peak,std::abs(source->audio.getSample(ch,n)));source->wave[bin]=peak;}cache[path]=source;return source;}
 void load(int index,const std::string& path,double start=0){auto& t=tracks.at(index);if(t.clips.size()>=64)throw std::runtime_error("Mỗi track tối đa 64 clip");Clip clip{nextClipId++,readSource(path),start,0,0};validateClip(clip);t.clips.push_back(clip);}
 TimelineJson clipInfo(const Clip& c,bool state){TimelineJson info={{"id",c.id},{"path",c.source->path},{"start",c.start},{"trimIn",c.trimIn},{"trimOut",c.trimOut},{"sourceDuration",c.source->audio.getNumSamples()/c.source->rate},{"duration",clipDuration(c)}};if(!state)info["wave"]=c.source->wave;return info;}
 TimelineJson trackInfo(int index,bool state=false){auto& t=tracks.at(index);TimelineJson inserts=TimelineJson::array();for(auto& s:t.inserts){TimelineJson a={{"path",s.path},{"on",s.on},{"bypass",s.bypass},{"parameters",TimelineJson::array()}};if(s.plugin){for(auto* p:s.plugin->getParameters())a["parameters"].push_back({{"name",p->getName(60).toStdString()},{"value",p->getValue()}});if(state){juce::MemoryBlock b;s.plugin->getStateInformation(b);a["state"]=b.toBase64Encoding().toStdString();}}inserts.push_back(a);}TimelineJson info={{"index",index},{"clips",TimelineJson::array()},{"gain",t.gain},{"pan",t.pan},{"mute",t.mute},{"solo",t.solo},{"fx",t.fx},{"inserts",inserts}};for(auto& c:t.clips)info["clips"].push_back(clipInfo(c,state));return info;}
 TimelineJson info(bool state=false){TimelineJson array=TimelineJson::array();for(int i=0;i<4;++i)array.push_back(trackInfo(i,state));return {{"version",2},{"tracks",array},{"position",position.load()},{"duration",duration()},{"playing",playing.load()},{"recording",recording.load()},{"armed",armed},{"recordStart",recordStart},{"drops",drops.load()}};}
 void loadInsert(int track,int slot,const std::string& path,const std::string& state=""){juce::VST3PluginFormat format;juce::OwnedArray<juce::PluginDescription> found;format.findAllTypesForFile(found,juce::String(path));if(found.isEmpty())throw std::runtime_error("Không có VST3 tương thích: "+path);juce::String error;auto plugin=formats.createPluginInstance(*found[0],rate,block,error);if(!plugin)throw std::runtime_error(error.toStdString());if(!plugin->setBusesLayout({{juce::AudioChannelSet::stereo()},{juce::AudioChannelSet::stereo()}}))throw std::runtime_error("VST3 phải hỗ trợ stereo in/out");plugin->setRateAndBufferSizeDetails(rate,block);plugin->prepareToPlay(rate,block);if(!state.empty()){juce::MemoryBlock b;if(!b.fromBase64Encoding(state))throw std::runtime_error("VST state không hợp lệ");plugin->setStateInformation(b.getData(),int(b.getSize()));}auto& s=tracks.at(track).inserts.at(slot);s.plugin=std::move(plugin);s.path=path;s.on=true;s.bypass=false;}
 void restore(const TimelineJson& data){requireStopped();int version=data.value("version",0);if((version!=1&&version!=2)||!data.contains("tracks")||data["tracks"].size()!=4)throw std::runtime_error("Dự án thu âm cần 4 track");for(auto& t:tracks)t.clips.clear();cache.clear();for(int i=0;i<4;++i){auto c=data["tracks"][i];edit(i,c);auto& t=tracks[i];auto list=c.value("clips",TimelineJson::array());if(version==1&&!c.value("path",std::string()).empty())list.push_back(c);if(!list.is_array()||list.size()>64)throw std::runtime_error("Danh sách clip không hợp lệ");for(auto a:list){Clip clip{nextClipId++,readSource(a.at("path")),a.value("start",0.),a.value("trimIn",0.),a.value("trimOut",0.)};validateClip(clip);t.clips.push_back(clip);}for(auto& insert:t.inserts)insert=Insert{};if(c.contains("inserts")){if(c["inserts"].size()!=4)throw std::runtime_error("Track cần 4 VST slots");for(int j=0;j<4;++j){auto a=c["inserts"][j];auto p=a.value("path",std::string());if(!p.empty())loadInsert(i,j,p,a.value("state",std::string()));t.inserts[j].on=a.value("on",true);t.inserts[j].bypass=a.value("bypass",false);}}}position=std::clamp(data.value("position",0.),0.,1800.);resetEffects();}
 void edit(int index,const TimelineJson& c){auto& t=tracks.at(index);auto range=[&](const char* name,double lo,double hi){if(c.contains(name)&&(!c[name].is_number()||!std::isfinite(c[name].get<double>())||c[name].get<double>()<lo||c[name].get<double>()>hi))throw std::runtime_error(std::string("Thông số track không hợp lệ: ")+name);};range("gain",0,2);range("pan",-1,1);range("start",0,1800);range("trimIn",0,1800);range("trimOut",0,1800);for(auto k:{"mute","solo"})if(c.contains(k)&&!c[k].is_boolean())throw std::runtime_error("Mute/Solo không hợp lệ");auto f=t.fx;f.update(c.value("fx",TimelineJson::object()));for(auto k:{"enabled","gate","compressor","eq","deesser","tune","reverb","autoKey","minor"})if(f.contains(k)&&!f[k].is_boolean())throw std::runtime_error("FX toggle không hợp lệ");auto fr=[&](const char* k,double lo,double hi){if(f.contains(k)&&(!f[k].is_number()||f[k].get<double>()<lo||f[k].get<double>()>hi))throw std::runtime_error("FX parameter không hợp lệ");};fr("key",0,11);fr("essAmount",0,1);fr("gateDb",-80,0);fr("compressorDb",-60,0);fr("ratio",1,20);fr("reverbWet",0,1);fr("tuneStrength",0,1);fr("tuneSpeed",1,250);if(f.contains("eqGains")){if(f["eqGains"].size()!=13)throw std::runtime_error("EQ cần 13 band");for(auto g:f["eqGains"])if(!g.is_number()||std::abs(g.get<float>())>18)throw std::runtime_error("EQ gain không hợp lệ");}t.gain=c.value("gain",t.gain);t.pan=c.value("pan",t.pan);t.mute=c.value("mute",t.mute);t.solo=c.value("solo",t.solo);if(c.contains("start")||c.contains("trimIn")||c.contains("trimOut")){if(!t.clips.empty())editClip(index,c.value("clip",t.clips.front().id),c);}t.fx=f;applyFx(t);}
 void beginRecord(int track,const std::string& path){requireStopped();if(track<0||track>3)throw std::runtime_error("Chọn track hợp lệ để thu");if(tracks[track].clips.size()>=64)throw std::runtime_error("Track đã đủ 64 clip");juce::File file(path);if(file.existsAsFile())throw std::runtime_error("File thu đã tồn tại");auto stream=file.createOutputStream();if(!stream)throw std::runtime_error("Không tạo được WAV thu mic");juce::WavAudioFormat wav;auto w=std::unique_ptr<juce::AudioFormatWriter>(wav.createWriterFor(stream.get(),rate,1,24,{},0));if(!w)throw std::runtime_error("Không tạo được WAV 24-bit");stream.release();writer=std::make_unique<juce::AudioFormatWriter::ThreadedWriter>(w.release(),disk,131072);armed=track;recordPath=path;recordStart=position.load();drops=0;recording=true;playing=true;resetEffects();}
 void stop(){playing=false;if(recording.exchange(false)){writer.reset();load(armed,recordPath,std::max(0.,recordStart-recordLatency));auto& c=tracks[armed].clips.back();c.trimIn=std::min(c.source->audio.getNumSamples()/c.source->rate,std::max(0.,recordLatency-recordStart));}resetEffects();}
 void render(int n,const float* mic){mix.clear();if(!playing){for(auto& t:tracks)t.peak=0;return;}const double base=position.load();if(recording&&writer&&mic){if(mic!=capture.getReadPointer(0))capture.copyFrom(0,0,mic,n);if(!writer->write(capture.getArrayOfReadPointers(),n))++drops;}bool solo=false;for(auto& t:tracks)solo|=t.solo;for(int k=0;k<4;++k){auto& t=tracks[k];t.work.clear();if(recording&&k==armed){t.peak=mic?capture.getMagnitude(0,n):0;continue;}if(t.mute||(solo&&!t.solo)){t.peak=0;continue;}bool fxOn=t.fx.value("enabled",false);for(int i=0;i<n;++i){float l=0,r=0;for(const auto& clip:t.clips){const auto& source=*clip.source;double time=base+i/rate-clip.start;double frame=(time+clip.trimIn)*source.rate;const double end=source.audio.getNumSamples()-clip.trimOut*source.rate;if(time>=0&&frame>=0&&frame<end){int a=int(frame),b=std::min(a+1,source.audio.getNumSamples()-1);float f=float(frame-a);l+=source.audio.getSample(0,a)*(1-f)+source.audio.getSample(0,b)*f;r+=source.audio.getSample(1,a)*(1-f)+source.audio.getSample(1,b)*f;}}if(fxOn){float v=t.dsp.process((l+r)*.5f);l=r=v;}t.work.setSample(0,i,l);t.work.setSample(1,i,r);}juce::AudioBuffer<float> b(t.work.getArrayOfWritePointers(),2,n);midi.clear();for(auto& s:t.inserts)if(s.plugin&&s.on&&!s.bypass)s.plugin->processBlock(b,midi);float peak=0;float left=t.gain*(t.pan>0?1-t.pan:1),right=t.gain*(t.pan<0?1+t.pan:1);for(int i=0;i<n;++i){float l=t.work.getSample(0,i)*left,r=t.work.getSample(1,i)*right;mix.addSample(0,i,l);mix.addSample(1,i,r);peak=std::max({peak,std::abs(l),std::abs(r)});}t.peak=peak;}position=base+n/rate;if(!recording&&position.load()>=duration()+2)playing=false;}
 void exportMix(const std::string& path,float masterGain=1){requireStopped();if(duration()<=0)throw std::runtime_error("Timeline chưa có audio");juce::File file(path);if(file.existsAsFile())throw std::runtime_error("File xuất đã tồn tại");auto stream=file.createOutputStream();if(!stream)throw std::runtime_error("Không tạo được file xuất");juce::WavAudioFormat wav;auto w=std::unique_ptr<juce::AudioFormatWriter>(wav.createWriterFor(stream.get(),rate,2,24,{},0));if(!w)throw std::runtime_error("Không tạo được WAV xuất");stream.release();double old=position.load();position=0;playing=true;resetEffects();try{int64_t frames=int64_t((duration()+2)*rate);for(int64_t i=0;i<frames;i+=block){int n=int(std::min<int64_t>(block,frames-i));render(n,nullptr);for(int ch=0;ch<2;++ch)for(int a=0;a<n;++a){float v=mix.getSample(ch,a)*masterGain;mix.setSample(ch,a,std::clamp(std::isfinite(v)?v:0.f,-.97f,.97f));}if(!w->writeFromAudioSampleBuffer(mix,0,n))throw std::runtime_error("Lỗi ghi WAV xuất");}}catch(...){playing=false;position=old;resetEffects();throw;}playing=false;position=old;resetEffects();}
};
