#pragma once
#include <juce_audio_utils/juce_audio_utils.h>
#include <nlohmann/json.hpp>
#include "dsp.h"
using TimelineJson=nlohmann::json;
// All edits/file IO run with the device callback detached. Only render() runs on audio thread.
class Timeline {
public:
 struct Insert {std::unique_ptr<juce::AudioPluginInstance> plugin;std::string path;bool on=true,bypass=false;};
 struct Track {juce::AudioBuffer<float> audio,work;double sourceRate=48000,start=0,trimIn=0,trimOut=0;float gain=1,pan=0;bool mute=false,solo=false;std::string path;TimelineJson fx;VocalDSP dsp;std::array<Insert,4> inserts;std::atomic<float> peak{0};};
 std::array<Track,4> tracks;juce::AudioBuffer<float> mix,capture;juce::MidiBuffer midi;
 std::atomic<bool> playing{false},recording{false};std::atomic<double> position{0};std::atomic<unsigned> drops{0};
 int armed=1;double rate=48000,recordStart=0,recordLatency=0;int block=512;std::string recordPath;std::unique_ptr<juce::AudioFormatWriter::ThreadedWriter> writer;juce::TimeSliceThread& disk;juce::AudioPluginFormatManager& formats;juce::AudioFormatManager readers;
 explicit Timeline(juce::TimeSliceThread& d,juce::AudioPluginFormatManager& f):disk(d),formats(f){readers.registerBasicFormats();for(auto& t:tracks)t.fx={{"enabled",false},{"gate",false},{"compressor",false},{"eq",false},{"deesser",false},{"tune",false},{"reverb",false},{"autoKey",true},{"key",0},{"minor",false},{"gateDb",-50},{"compressorDb",-18},{"ratio",3},{"reverbWet",.18},{"tuneStrength",.8},{"tuneSpeed",35},{"eqGains",std::vector<float>(13,0)}};prepare(rate,block);}
 void applyFx(Track& t){auto& f=t.fx;t.dsp.gate=f.value("gate",false);t.dsp.compressor=f.value("compressor",false);t.dsp.equalizer=f.value("eq",false);t.dsp.deesser=f.value("deesser",false);t.dsp.tune=f.value("tune",false);t.dsp.reverb=f.value("reverb",false);t.dsp.autoKey=f.value("autoKey",true);t.dsp.key=f.value("key",0);t.dsp.minor=f.value("minor",false);t.dsp.gateDb=f.value("gateDb",-50.f);t.dsp.threshold=f.value("compressorDb",-18.f);t.dsp.ratio=f.value("ratio",3.f);t.dsp.wet=f.value("reverbWet",.18f);t.dsp.tuneStrength=f.value("tuneStrength",.8f);t.dsp.tuneSpeed=f.value("tuneSpeed",35.f);auto gains=f.value("eqGains",std::vector<float>(13,0));for(int i=0;i<13;++i)t.dsp.eq[i].peak(rate,VocalDSP::hz[i],gains.at(i));}
 void prepare(double sr,int bs){rate=sr;block=bs;mix.setSize(2,std::max(8192,bs));capture.setSize(1,std::max(8192,bs));for(auto& t:tracks){t.work.setSize(2,std::max(8192,bs));t.dsp.prepare(rate);applyFx(t);for(auto& s:t.inserts)if(s.plugin){s.plugin->releaseResources();s.plugin->setRateAndBufferSizeDetails(rate,block);s.plugin->prepareToPlay(rate,block);}}}
 double clipDuration(const Track& t)const{return std::max(0.,t.audio.getNumSamples()/t.sourceRate-t.trimIn-t.trimOut);}
 double duration()const{double result=0;for(auto& t:tracks)result=std::max(result,t.start+clipDuration(t));return result;}
 void resetEffects(){for(auto& t:tracks){t.dsp.prepare(rate);applyFx(t);for(auto& s:t.inserts)if(s.plugin)s.plugin->reset();}}
 void requireStopped(){if(playing||recording)throw std::runtime_error("Dừng timeline trước khi chỉnh clip, nạp file hoặc VST");}
 void load(int index,const std::string& path){auto& t=tracks.at(index);std::unique_ptr<juce::AudioFormatReader> reader(readers.createReaderFor(juce::File(path)));if(!reader)throw std::runtime_error("Không đọc được beat/audio. Chọn WAV, MP3, FLAC hoặc AIFF: "+path);if(reader->lengthInSamples<=0||reader->lengthInSamples>int64_t(reader->sampleRate*1800)||reader->lengthInSamples>32000000)throw std::runtime_error("File quá dài: tối đa 30 phút và 32 triệu mẫu mỗi track");int64_t total=reader->lengthInSamples;for(int i=0;i<4;++i)if(i!=index)total+=tracks[i].audio.getNumSamples();if(total>64000000)throw std::runtime_error("Tổng audio vượt giới hạn bộ nhớ 512 MB");juce::AudioBuffer<float> buffer(2,int(reader->lengthInSamples));if(!reader->read(&buffer,0,buffer.getNumSamples(),0,true,true))throw std::runtime_error("Không đọc đủ dữ liệu audio");t.audio=std::move(buffer);t.sourceRate=reader->sampleRate;t.path=path;t.trimIn=t.trimOut=0;}
 TimelineJson trackInfo(int index,bool state=false){auto& t=tracks.at(index);TimelineJson inserts=TimelineJson::array();for(auto& s:t.inserts){TimelineJson a={{"path",s.path},{"on",s.on},{"bypass",s.bypass},{"parameters",TimelineJson::array()}};if(s.plugin){for(auto* p:s.plugin->getParameters())a["parameters"].push_back({{"name",p->getName(60).toStdString()},{"value",p->getValue()}});if(state){juce::MemoryBlock b;s.plugin->getStateInformation(b);a["state"]=b.toBase64Encoding().toStdString();}}inserts.push_back(a);}TimelineJson info={{"index",index},{"path",t.path},{"start",t.start},{"trimIn",t.trimIn},{"trimOut",t.trimOut},{"sourceDuration",t.audio.getNumSamples()/t.sourceRate},{"duration",clipDuration(t)},{"gain",t.gain},{"pan",t.pan},{"mute",t.mute},{"solo",t.solo},{"fx",t.fx},{"inserts",inserts}};if(!state){TimelineJson wave=TimelineJson::array();int count=t.audio.getNumSamples();for(int bin=0;bin<800;++bin){float peak=0;int a=int(int64_t(bin)*count/800),b=int(int64_t(bin+1)*count/800);for(int n=a;n<b;++n)for(int ch=0;ch<2;++ch)peak=std::max(peak,std::abs(t.audio.getSample(ch,n)));wave.push_back(peak);}info["wave"]=wave;}return info;}
 TimelineJson info(bool state=false){TimelineJson array=TimelineJson::array();for(int i=0;i<4;++i)array.push_back(trackInfo(i,state));return {{"version",1},{"tracks",array},{"position",position.load()},{"duration",duration()},{"playing",playing.load()},{"recording",recording.load()},{"armed",armed},{"recordStart",recordStart},{"drops",drops.load()}};}
 void loadInsert(int track,int slot,const std::string& path,const std::string& state=""){juce::VST3PluginFormat format;juce::OwnedArray<juce::PluginDescription> found;format.findAllTypesForFile(found,juce::String(path));if(found.isEmpty())throw std::runtime_error("Không có VST3 tương thích: "+path);juce::String error;auto plugin=formats.createPluginInstance(*found[0],rate,block,error);if(!plugin)throw std::runtime_error(error.toStdString());if(!plugin->setBusesLayout({{juce::AudioChannelSet::stereo()},{juce::AudioChannelSet::stereo()}}))throw std::runtime_error("VST3 phải hỗ trợ stereo in/out");plugin->setRateAndBufferSizeDetails(rate,block);plugin->prepareToPlay(rate,block);if(!state.empty()){juce::MemoryBlock b;if(!b.fromBase64Encoding(state))throw std::runtime_error("VST state không hợp lệ");plugin->setStateInformation(b.getData(),int(b.getSize()));}auto& s=tracks.at(track).inserts.at(slot);s.plugin=std::move(plugin);s.path=path;s.on=true;s.bypass=false;}
 void restore(const TimelineJson& data){requireStopped();if(data.value("version",0)!=1||!data.contains("tracks")||data["tracks"].size()!=4)throw std::runtime_error("Dự án thu âm cần 4 track");for(int i=0;i<4;++i){auto c=data["tracks"][i];edit(i,c);auto& t=tracks[i];auto path=c.value("path",std::string());if(path.empty()){t.audio.setSize(2,0);t.path.clear();}else load(i,path);t.trimIn=c.value("trimIn",0.);t.trimOut=c.value("trimOut",0.);if(t.trimIn+t.trimOut>t.audio.getNumSamples()/t.sourceRate)throw std::runtime_error("Điểm cắt clip vượt quá độ dài file");for(auto& s:t.inserts)s=Insert{};if(c.contains("inserts")){if(c["inserts"].size()!=4)throw std::runtime_error("Track cần 4 VST slots");for(int j=0;j<4;++j){auto a=c["inserts"][j];auto p=a.value("path",std::string());if(!p.empty())loadInsert(i,j,p,a.value("state",std::string()));t.inserts[j].on=a.value("on",true);t.inserts[j].bypass=a.value("bypass",false);}}}position=std::clamp(data.value("position",0.),0.,1800.);resetEffects();}
 void edit(int index,const TimelineJson& c){auto& t=tracks.at(index);auto range=[&](const char* name,double lo,double hi){if(c.contains(name)&&(!c[name].is_number()||!std::isfinite(c[name].get<double>())||c[name].get<double>()<lo||c[name].get<double>()>hi))throw std::runtime_error(std::string("Thông số track không hợp lệ: ")+name);};range("gain",0,2);range("pan",-1,1);range("start",0,1800);range("trimIn",0,1800);range("trimOut",0,1800);for(auto k:{"mute","solo"})if(c.contains(k)&&!c[k].is_boolean())throw std::runtime_error("Mute/Solo không hợp lệ");auto f=c.value("fx",t.fx);for(auto k:{"enabled","gate","compressor","eq","deesser","tune","reverb","autoKey","minor"})if(f.contains(k)&&!f[k].is_boolean())throw std::runtime_error("FX toggle không hợp lệ");auto fr=[&](const char* k,double lo,double hi){if(f.contains(k)&&(!f[k].is_number()||f[k].get<double>()<lo||f[k].get<double>()>hi))throw std::runtime_error("FX parameter không hợp lệ");};fr("key",0,11);fr("gateDb",-80,0);fr("compressorDb",-60,0);fr("ratio",1,20);fr("reverbWet",0,1);fr("tuneStrength",0,1);fr("tuneSpeed",1,250);if(f.contains("eqGains")){if(f["eqGains"].size()!=13)throw std::runtime_error("EQ cần 13 band");for(auto g:f["eqGains"])if(!g.is_number()||std::abs(g.get<float>())>18)throw std::runtime_error("EQ gain không hợp lệ");}t.gain=c.value("gain",t.gain);t.pan=c.value("pan",t.pan);t.mute=c.value("mute",t.mute);t.solo=c.value("solo",t.solo);t.start=c.value("start",t.start);t.trimIn=c.value("trimIn",t.trimIn);t.trimOut=c.value("trimOut",t.trimOut);t.fx=f;applyFx(t);}
 void beginRecord(int track,const std::string& path){requireStopped();if(track<1||track>3)throw std::runtime_error("Chọn track Mic 1/2/3 để thu");juce::File file(path);if(file.existsAsFile())throw std::runtime_error("File thu đã tồn tại");auto stream=file.createOutputStream();if(!stream)throw std::runtime_error("Không tạo được WAV thu mic");juce::WavAudioFormat wav;auto w=std::unique_ptr<juce::AudioFormatWriter>(wav.createWriterFor(stream.get(),rate,1,24,{},0));if(!w)throw std::runtime_error("Không tạo được WAV 24-bit");stream.release();writer=std::make_unique<juce::AudioFormatWriter::ThreadedWriter>(w.release(),disk,131072);armed=track;recordPath=path;recordStart=position.load();drops=0;recording=true;playing=true;resetEffects();}
 void stop(){playing=false;if(recording.exchange(false)){writer.reset();load(armed,recordPath);tracks[armed].start=std::max(0.,recordStart-recordLatency);tracks[armed].trimIn=std::min(tracks[armed].audio.getNumSamples()/tracks[armed].sourceRate,std::max(0.,recordLatency-recordStart));}resetEffects();}
 void render(int n,const float* mic){mix.clear();if(!playing)return;const double base=position.load();if(recording&&writer&&mic){if(mic!=capture.getReadPointer(0))capture.copyFrom(0,0,mic,n);if(!writer->write(capture.getArrayOfReadPointers(),n))++drops;}bool solo=false;for(auto& t:tracks)solo|=t.solo;for(int k=0;k<4;++k){auto& t=tracks[k];t.work.clear();if(recording&&k==armed){t.peak=mic?capture.getMagnitude(0,n):0;continue;}if(t.mute||(solo&&!t.solo)){t.peak=0;continue;}const auto end=t.audio.getNumSamples()-t.trimOut*t.sourceRate;bool fxOn=t.fx.value("enabled",false);for(int i=0;i<n;++i){double time=base+i/rate-t.start;double frame=(time+t.trimIn)*t.sourceRate;float l=0,r=0;if(time>=0&&frame>=0&&frame<end){int a=int(frame),b=std::min(a+1,t.audio.getNumSamples()-1);float f=float(frame-a);l=t.audio.getSample(0,a)*(1-f)+t.audio.getSample(0,b)*f;r=t.audio.getSample(1,a)*(1-f)+t.audio.getSample(1,b)*f;}if(fxOn){float v=t.dsp.process((l+r)*.5f);l=r=v;}t.work.setSample(0,i,l);t.work.setSample(1,i,r);}juce::AudioBuffer<float> b(t.work.getArrayOfWritePointers(),2,n);midi.clear();for(auto& s:t.inserts)if(s.plugin&&s.on&&!s.bypass)s.plugin->processBlock(b,midi);float peak=0;float left=t.gain*(t.pan>0?1-t.pan:1),right=t.gain*(t.pan<0?1+t.pan:1);for(int i=0;i<n;++i){float l=t.work.getSample(0,i)*left,r=t.work.getSample(1,i)*right;mix.addSample(0,i,l);mix.addSample(1,i,r);peak=std::max({peak,std::abs(l),std::abs(r)});}t.peak=peak;}position=base+n/rate;if(!recording&&position.load()>=duration()+2)playing=false;}
 void exportMix(const std::string& path,float masterGain=1){requireStopped();if(duration()<=0)throw std::runtime_error("Timeline chưa có audio");juce::File file(path);if(file.existsAsFile())throw std::runtime_error("File xuất đã tồn tại");auto stream=file.createOutputStream();if(!stream)throw std::runtime_error("Không tạo được file xuất");juce::WavAudioFormat wav;auto w=std::unique_ptr<juce::AudioFormatWriter>(wav.createWriterFor(stream.get(),rate,2,24,{},0));if(!w)throw std::runtime_error("Không tạo được WAV xuất");stream.release();double old=position.load();position=0;playing=true;resetEffects();try{int64_t frames=int64_t((duration()+2)*rate);for(int64_t i=0;i<frames;i+=block){int n=int(std::min<int64_t>(block,frames-i));render(n,nullptr);for(int ch=0;ch<2;++ch)for(int a=0;a<n;++a){float v=mix.getSample(ch,a)*masterGain;mix.setSample(ch,a,std::clamp(std::isfinite(v)?v:0.f,-.97f,.97f));}if(!w->writeFromAudioSampleBuffer(mix,0,n))throw std::runtime_error("Lỗi ghi WAV xuất");}}catch(...){playing=false;position=old;resetEffects();throw;}playing=false;position=old;resetEffects();}
};
