#pragma once
#include "timeline.h"
#include "soundboard.h"
#include <stdexcept>
inline int runTimelineTest(){
 juce::TimeSliceThread disk("Timeline test disk");disk.startThread();juce::AudioPluginFormatManager formats;formats.addFormat(new juce::VST3PluginFormat());
 auto folder=juce::File::getSpecialLocation(juce::File::tempDirectory).getChildFile("HNStudio-timeline-"+juce::String(juce::Time::currentTimeMillis()));folder.createDirectory();
 try{
  auto check=[](bool condition,const char* message){if(!condition)throw std::runtime_error(message);};
  auto source=folder.getChildFile("beat.wav");{auto stream=source.createOutputStream();juce::WavAudioFormat wav;std::unique_ptr<juce::AudioFormatWriter> writer(wav.createWriterFor(stream.get(),24000,2,24,{},0));check(bool(writer),"test WAV writer");stream.release();juce::AudioBuffer<float> b(2,24000);for(int i=0;i<24000;++i){b.setSample(0,i,.2f);b.setSample(1,i,.4f);}check(writer->writeFromAudioSampleBuffer(b,0,24000),"source write");}
  Timeline timeline(disk,formats);timeline.prepare(48000,512);timeline.load(0,source.getFullPathName().toStdString());timeline.playing=true;timeline.render(512,nullptr);check(std::abs(timeline.mix.getSample(0,200)-.2f)<.0001f,"resampling left");check(std::abs(timeline.mix.getSample(1,200)-.4f)<.0001f,"resampling right");timeline.stop();timeline.edit(0,{{"start",.5},{"trimIn",.1},{"trimOut",.2}});timeline.position=0;timeline.playing=true;timeline.render(512,nullptr);check(timeline.mix.getMagnitude(0,512)==0,"clip start silence");timeline.stop();check(std::abs(timeline.duration()-1.2)<.0001,"trim duration");timeline.position=.5;timeline.playing=true;timeline.render(512,nullptr);check(std::abs(timeline.mix.getSample(0,100)-.2f)<.0001,"clip start playback");timeline.stop();timeline.edit(0,{{"mute",true}});timeline.playing=true;timeline.render(512,nullptr);check(timeline.mix.getMagnitude(0,512)==0,"mute");timeline.stop();timeline.edit(0,{{"mute",false},{"pan",1}});timeline.position=.5;timeline.playing=true;timeline.render(512,nullptr);check(timeline.mix.getMagnitude(0,0,512)==0&&timeline.mix.getMagnitude(1,0,512)>.39,"pan");timeline.stop();timeline.edit(0,{{"pan",0}});
  auto take=folder.getChildFile("mic.wav");timeline.position=.25;timeline.beginRecord(1,take.getFullPathName().toStdString());juce::AudioBuffer<float> mic(1,512);for(int i=0;i<512;++i)mic.setSample(0,i,.1f*std::sin(float(i)*.05f));for(int i=0;i<12;++i)timeline.render(512,mic.getReadPointer(0));timeline.stop();check(timeline.drops==0,"record queue dropped");check(timeline.tracks[1].clips[0].source->audio.getNumSamples()==6144,"record sample count");check(std::abs(timeline.tracks[1].clips[0].start-.25)<1e-6,"record start position");check(std::abs(timeline.tracks[1].clips[0].source->audio.getSample(0,100)-mic.getSample(0,100))<.0001,"dry microphone recording");
  timeline.edit(1,{{"solo",true},{"mute",false}});timeline.position=.6;timeline.playing=true;timeline.render(512,nullptr);check(timeline.mix.getMagnitude(0,512)==0,"solo excludes beat after mic clip end");timeline.stop();timeline.edit(1,{{"solo",false}});
  auto oldDuration=timeline.duration();int first=timeline.tracks[0].clips[0].id;timeline.splitClip(0,first,.85);check(timeline.tracks[0].clips.size()==2,"split creates two clips");check(std::abs(timeline.duration()-oldDuration)<.0001,"split preserves duration");int right=timeline.tracks[0].clips[1].id;timeline.moveClip(0,right,2,.85);check(timeline.tracks[2].clips.size()==1&&timeline.tracks[0].clips.size()==1,"move across tracks");check(timeline.tracks[2].clips[0].source==timeline.tracks[0].clips[0].source,"split shares source memory");timeline.position=.84;timeline.playing=true;timeline.render(512,nullptr);check(std::abs(timeline.mix.getSample(0,500)-.2f)<.0001,"split boundary plays continuously");timeline.stop();auto saved=timeline.info(true);Timeline restored(disk,formats);restored.prepare(48000,512);restored.restore(saved);check(restored.tracks[1].clips[0].source->audio.getNumSamples()==6144,"project audio restored");check(restored.tracks[0].clips[0].trimIn==.1,"project trim restored");
  auto mix=folder.getChildFile("mix.wav");restored.exportMix(mix.getFullPathName().toStdString());juce::WavAudioFormat wav;std::unique_ptr<juce::AudioFormatReader> reader(wav.createReaderFor(new juce::FileInputStream(mix),true));check(bool(reader)&&reader->bitsPerSample==24&&reader->numChannels==2,"export WAV 24-bit stereo");juce::AudioBuffer<float> result(2,512);reader->read(&result,0,512,30000,true,true);check(result.getMagnitude(0,512)>.19,"export contains beat");reader.reset();
  bool invalid=false;try{timeline.edit(0,{{"gain",-1}});}catch(...){invalid=true;}check(invalid,"invalid gain rejected");
  Soundboard sounds;sounds.prepare(48000,512);for(int pad=0;pad<6;++pad){sounds.stop();sounds.trigger(pad);float peak=0;for(int block=0;block<10;++block){sounds.render(512);peak=std::max(peak,sounds.mix.getMagnitude(0,512));}check(peak>.001,"sound pad must output real samples");}sounds.stop();sounds.render(512);check(sounds.mix.getMagnitude(0,512)==0,"soundboard stop");
  folder.deleteRecursively();disk.stopThread(5000);std::cout<<"Timeline passed: rate conversion, clip offset/trim, mute/solo/pan, dry mic recording, project restore, 24-bit mix export\n";return 0;
 }catch(const std::exception& e){std::cerr<<"Timeline self-test failed: "<<e.what()<<"\n";folder.deleteRecursively();disk.stopThread(5000);return 1;}
}
