'use strict';
const $=id=>document.getElementById(id);let settings={backend:'ASIO',sendEnabled:false,micVolume:.8,musicVolume:.5,masterVolume:.7,gate:true,compressor:true,eq:true,deesser:true,tune:false,reverb:true,autoKey:false,key:'C',gateDb:-50,compressorDb:-18,ratio:3,essAmount:.5,reverbWet:.18,tuneStrength:.8,eqGains:Array(13).fill(0)};
let configured=false,portDriver="";
const routingIds=["micChannel","musicLeft","musicRight","monitorLeft","monitorRight","sendLeft","sendRight"];
let live=false,recording=false,ready=false,busy=false,telemetry={mic:0,music:0,master:0,waveform:Array(128).fill(0)},previousErrors='';
const logs=[];function log(message,error=false){logs.push(`${new Date().toLocaleTimeString()} ${error?'ERROR · ':''}${message}`);if(logs.length>200)logs.shift();$('log').textContent=logs.join('\n');$('log').scrollTop=$('log').scrollHeight;if(error)$('status').textContent=message;}
async function run(fn){if(busy){log('Chờ tác vụ audio hiện tại hoàn tất.');return null;}busy=true;try{return await fn();}catch(e){log(e.message,true);return null;}finally{busy=false;}}
function command(op,data){return window.studio.command(op,data);}
function fillSelect(id,list,indexed=false){const old=$(id).value;$(id).replaceChildren();list.forEach((name,i)=>{const option=document.createElement('option');option.value=indexed?i:name;option.textContent=indexed?`${i+1} · ${name}`:name;$(id).append(option);});if([...$(id).options].some(o=>o.value===old))$(id).value=old;}
function mode(){const asio=$('backend').value==='ASIO';$('asioRouting').hidden=!asio;for(const id of ['driver','ports','controlPanel'])$(id).hidden=!asio;for(const id of ['input','output'])$(id).disabled=asio||live||recording;$('routingNote').textContent=asio?'Windows phát nhạc vào thiết bị ASIOVADPRO của ASIO Link Pro → MUSIC input. Mic → MIC input. Master → Monitor và Live send. Trong bảng routing của driver, tắt đường nhạc đi thẳng ra loa để tránh hai tiếng. Driver ASIO Link Pro x64 phải được cài trước.':'WASAPI loopback sao chép âm thanh Windows; nhạc vẫn phát trực tiếp từ hệ thống. Chọn output khác để tránh nghe hai lần.';$('musicFlow').textContent=asio?'WINDOWS → ASIO LINK PRO → MUSIC INPUT → MUSIC VOLUME → MASTER':'WINDOWS → WASAPI LOOPBACK → MUSIC VOLUME → MASTER';}
async function readPorts(preserve=false){configured=false;const driver=$('driver').value;if(!driver)throw new Error('Chưa có driver ASIO x64. Cài ASIO Link Pro rồi Refresh.');const d=await command('ports',{driver});const same=preserve&&settings.driver===driver;const defaults={micChannel:['Input1',0],musicLeft:['LinkIn3',2],musicRight:['LinkIn4',3],monitorLeft:['Output1',0],monitorRight:['Output2',1],sendLeft:['LinkOut3',2],sendRight:['LinkOut4',3]};const norm=x=>x.toLowerCase().replace(/[^a-z0-9]/g,'');for(const id of routingIds){const list=id==='micChannel'||id.startsWith('music')?d.inputs:d.outputs;fillSelect(id,list,true);const [name,fallback]=defaults[id];const found=list.findIndex(x=>norm(x)===norm(name));const value=same&&settings[id]!==undefined?settings[id]:found>=0?found:fallback;$(id).value=String(value<list.length?value:0);}portDriver=driver;log(`ASIO ${driver}: ${d.inputs.length} inputs / ${d.outputs.length} outputs`);}
async function refresh(){configured=false;const d=await command('devices');fillSelect('input',d.inputs);fillSelect('output',d.outputs);fillSelect('driver',d.drivers||[]);if(settings.driver&&(d.drivers||[]).includes(settings.driver))$('driver').value=settings.driver;else{const link=(d.drivers||[]).find(x=>/asio.*link|link.*pro/i.test(x));if(link)$('driver').value=link;}mode();log(`Devices: ${d.inputs.length} input / ${d.outputs.length} output / ${(d.drivers||[]).length} ASIO`);if($('backend').value==='ASIO')await readPorts(true);}
function selected(){const c={backend:$('backend').value,input:$('input').value,output:$('output').value,driver:$('driver').value,sampleRate:Number($('sampleRate').value),bufferSize:Number($('bufferSize').value),sendEnabled:$('sendEnabled').checked};for(const id of routingIds)c[id]=Number($(id).value);return c;}
async function configure(){configured=false;if(live||recording)throw new Error('Tắt LIVE và REC trước khi đổi thiết bị.');if($('backend').value==='ASIO'){if(!$('driver').value)throw new Error('Chưa chọn driver ASIO x64.');if(portDriver!==$('driver').value)await readPorts(true);}else if(!$('output').value)throw new Error('Chưa chọn thiết bị output.');settings=await command('configure',{...settings,...selected()});configured=true;renderSettings();log(`Output: ${settings.output} · ${settings.sampleRate} Hz / ${settings.bufferSize} samples`);}
function slider(container,title,id,min,max,step){const label=document.createElement('label');label.textContent=title;const output=document.createElement('output');const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.step=step;input.dataset.param=id;input.value=settings[id];output.textContent=input.value;input.addEventListener('input',()=>output.textContent=input.value);input.addEventListener('change',()=>run(async()=>{const change={[id]:Number(input.value)};settings={...settings,...await command('params',change)};renderSettings();}));label.append(input,output);container.append(label);}
for(const [name,id]of [['MIC VOLUME','micVolume'],['MUSIC VOLUME','musicVolume'],['MASTER VOLUME','masterVolume']]){slider($('volumes'),name,id,0,1.5,.01);const meter=document.createElement('div');meter.className='meter';const key=id.replace('Volume','');meter.innerHTML=`<div class="meter-title">${name.split(' ')[0]}<span id="db-${key}">−∞ dB</span></div><div class="track"><div class="fill" id="meter-${key}"></div></div>`;$('meters').append(meter);}
const fx=[['NOISE GATE','gate','Threshold dB','gateDb',-80,-10,1],['COMPRESSOR','compressor','Threshold dB','compressorDb',-50,0,1],['DE-ESSER','deesser','Sibilance reduction','essAmount',0,1,.01],['PITCH CORRECTION','tune','Correction strength','tuneStrength',0,1,.01],['REVERB','reverb','Wet / dry','reverbWet',0,1,.01]];
for(const [name,id,label,param,min,max,step]of fx){const panel=document.createElement('section');panel.className='effect';panel.id=`fx-${id}`;panel.innerHTML=`<div class="section-title"><h3>${name}</h3><button class="toggle" data-toggle="${id}">ON</button></div>`;slider(panel,label,param,min,max,step);if(id==='compressor')slider(panel,'Ratio','ratio',1,12,.1);if(id==='tune'){const keyLabel=document.createElement('label');keyLabel.textContent='Musical key';const select=document.createElement('select');select.id='key';for(const key of ['C','Cm','D','Dm','E','Em','F','Fm']){const option=document.createElement('option');option.value=key;option.textContent=key;select.append(option);}select.addEventListener('change',()=>run(async()=>{settings={...settings,...await command('params',{key:select.value})};}));keyLabel.append(select);panel.append(keyLabel);const button=document.createElement('button');button.dataset.toggle='autoKey';button.className='toggle';button.textContent='AUTO KEY';panel.append(button);const hint=document.createElement('p');hint.className='note';hint.id='detected';hint.textContent='Auto Key ước lượng từ giọng hát; cần nhiều nốt.';panel.append(hint);}$('effects').append(panel);}
for(const [i,hz]of [40,63,100,160,250,400,630,1000,1600,2500,4000,6300,10000].entries()){const band=document.createElement('label');band.className='band';const output=document.createElement('output');output.id=`eq-value-${i}`;output.textContent='0 dB';const input=document.createElement('input');input.type='range';input.min=-18;input.max=18;input.step=.5;input.value=0;input.id=`eq-${i}`;input.addEventListener('input',()=>output.textContent=`${input.value} dB`);input.addEventListener('change',()=>run(async()=>{const gains=[...settings.eqGains];gains[i]=Number(input.value);settings={...settings,...await command('params',{eqGains:gains})};renderSettings();}));const text=document.createElement('span');text.textContent=hz>=1000?`${hz/1000}k`:hz;band.append(output,input,text);$('eq').append(band);}
function updateSlot(i,data){if(!data)return;const slot=$(`slot-${i}`);slot.querySelector('.slot-name').textContent=data.path?data.path.split(/[\\/]/).pop():'Empty · Load .vst3';slot.dataset.on=String(data.on);slot.dataset.bypass=String(data.bypass);slot.querySelector('[data-action=on]').classList.toggle('on',!!data.on&&!!data.path);slot.querySelector('[data-action=bypass]').classList.toggle('on',!!data.bypass);const params=slot.querySelector('.plugin-params');params.replaceChildren();for(const [j,p]of (data.parameters||[]).entries()){const label=document.createElement('label');label.textContent=p.name;const input=document.createElement('input');input.type='range';input.min=0;input.max=1;input.step=.001;input.value=p.value;input.addEventListener('change',()=>run(()=>window.studio.slot(i,'parameter',{parameter:j,value:Number(input.value)})));label.append(input);params.append(label);}}
for(let i=0;i<4;i++){const slot=document.createElement('div');slot.className='slot';slot.id=`slot-${i}`;slot.innerHTML=`<h2>SLOT 0${i+1}</h2><div class="slot-name">Empty · Load .vst3</div><div class="slot-buttons"><button data-action="load">Load</button><button data-action="on">ON/OFF</button><button data-action="bypass">Bypass</button><button data-action="remove">Remove</button></div><div class="plugin-params"></div>`;slot.dataset.on='true';slot.dataset.bypass='false';slot.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>run(async()=>{const action=button.dataset.action;const value=action==='on'?slot.dataset.on!=='true':slot.dataset.bypass!=='true';const data=await window.studio.slot(i,action,value);updateSlot(i,data);if(data)log(`VST3 slot ${i+1}: ${action}`);})));$('slots').append(slot);}
document.querySelectorAll('[data-toggle]').forEach(button=>button.addEventListener('click',()=>run(async()=>{const id=button.dataset.toggle;settings={...settings,...await command('params',{[id]:!settings[id]})};renderSettings();})));
function renderSettings(){document.querySelectorAll('[data-param]').forEach(input=>{input.value=settings[input.dataset.param];input.nextElementSibling.textContent=input.value;});document.querySelectorAll('[data-toggle]').forEach(button=>{const id=button.dataset.toggle;button.classList.toggle('on',!!settings[id]);button.textContent=id==='autoKey'?`AUTO KEY ${settings[id]?'ON':'OFF'}`:settings[id]?'ON':'OFF';$(`fx-${id}`)?.classList.toggle('on',!!settings[id]);if(id==='eq')$('eqPanel').classList.toggle('on',!!settings[id]);});for(let i=0;i<13;i++){$(`eq-${i}`).value=settings.eqGains[i];$(`eq-value-${i}`).textContent=`${settings.eqGains[i]} dB`;}$('key').value=settings.key;for(const id of ['backend','driver',...routingIds,'input','output','sampleRate','bufferSize'])if(settings[id]!==undefined)$(id).value=settings[id];$('sendEnabled').checked=!!settings.sendEnabled;mode();$('latency').textContent=`${settings.sampleRate||48000} Hz / ${settings.bufferSize||512} samples`;}
function renderTransport(){ $('live').classList.toggle('on',live);$('live').textContent=live?'◉ LIVE ON':'◉ LIVE OFF';$('rec').classList.toggle('on',recording);$('rec').textContent=recording?'■ STOP REC':'● REC WAV 24-bit';for(const id of ['backend','driver',...routingIds,'sendEnabled','ports','controlPanel','input','output','sampleRate','bufferSize','apply','refresh','load'])$(id).disabled=live||recording;mode();}
for(const id of ['backend','driver',...routingIds,'sendEnabled','input','output','sampleRate','bufferSize'])$(id).addEventListener('change',()=>{configured=false;mode();});
$('driver').addEventListener('change',()=>run(()=>readPorts(false)));$('backend').addEventListener('change',()=>{if($('backend').value==='ASIO'&&$('driver').value)run(()=>readPorts(true));});
$('ports').onclick=()=>run(()=>readPorts(true));$('controlPanel').onclick=()=>run(async()=>{if(!configured)await configure();const r=await command('control-panel');configured=false;log(r.opened?'Driver panel opened. Apply audio again after changing routing.':'Driver has no control panel.',!r.opened);});
$('refresh').onclick=()=>run(refresh);$('apply').onclick=()=>run(configure);$('test').onclick=()=>run(async()=>{if(!configured)await configure();const r=await command('test');log(`TEST 440 Hz → ${r.output} (2 giây)`);});
$('live').onclick=()=>run(async()=>{if(!ready)throw new Error('Native audio chưa sẵn sàng.');if(!configured)await configure();const r=await command('live',{on:!live});live=r.live;renderTransport();$('status').textContent=live?'LIVE · Native audio processing':'Audio ready · LIVE OFF';log(live?`LIVE ON · ${r.source}`:'LIVE OFF');});
$('rec').onclick=()=>run(async()=>{const r=await window.studio.record(!recording);if(r){recording=r.recording;renderTransport();log(recording?'Recording Master WAV 24-bit':'WAV đã hoàn tất');}});
for(const action of ['save','load'])$(action).onclick=()=>run(async()=>{const result=await window.studio.project(action);if(result){if(action==='load'){settings={...settings,...result,backend:result.backend||'Windows Audio'};renderSettings();if(settings.backend==='ASIO')await readPorts(true);configured=true;result.slots?.forEach((s,i)=>updateSlot(i,s));}log(`Project ${action} complete`);}});
$('exportLog').onclick=()=>run(()=>window.studio.exportLog());
window.studio.onEvent(data=>{if(data.event==='ready'){ready=true;$('status').textContent='Native audio ready · Chọn thiết bị rồi Apply';log(data.backend);run(refresh);}else if(data.event==='error')log(data.message,true);else if(data.event==='meters'){telemetry=data;const errors=`${data.loopbackError}/${data.captureDrops}/${data.recordDrops}/${data.underruns}`;if(errors!==previousErrors&&(data.loopbackError||data.captureDrops||data.recordDrops||data.underruns)){log(`Audio diagnostics: loopback error=${data.loopbackError}, capture drops=${data.captureDrops}, WAV drops=${data.recordDrops}, oversized blocks=${data.underruns}`,true);previousErrors=errors;}const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];if(settings.autoKey)$('detected').textContent=`Auto Key estimate: ${names[data.detectedKey%12]}${data.detectedKey>=12?'m':''}`;}});
const canvas=$('wave'),ctx=canvas.getContext('2d');function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#1c2c44';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();const gradient=ctx.createLinearGradient(0,0,w,0);gradient.addColorStop(0,'#35e8fa');gradient.addColorStop(.4,'#4074ff');gradient.addColorStop(.7,'#995aff');gradient.addColorStop(1,'#f447c7');ctx.strokeStyle=gradient;ctx.shadowColor='#35e8fa';ctx.shadowBlur=12;ctx.lineWidth=2;ctx.beginPath();telemetry.waveform.forEach((v,i)=>{const x=i*w/127,y=h/2-v*h*.45;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();ctx.shadowBlur=0;for(const id of ['mic','music','master']){const value=telemetry[id]||0;$(`meter-${id}`).style.width=`${Math.min(100,value*100)}%`;$(`db-${id}`).textContent=value>.00001?`${(20*Math.log10(value)).toFixed(1)} dB`:'−∞ dB';}requestAnimationFrame(draw);}renderSettings();draw();
