 'use strict';
const $=id=>document.getElementById(id);
let settings={delay:false,delayWet:.2,delayMs:380,delayFeedback:.32,delayBpm:120,delaySync:false,delayDivision:1,delayDuck:.45,delayTone:.55,delayPingPong:true,reverbWidth:1,masterFx:false,masterLow:0,masterMid:0,masterHigh:0,masterWidth:1,masterThick:.12,masterGlue:.2,masterLoud:0,aiAssist:true,highpass:false,warmth:false,air:false,highpassHz:80,warmthAmount:.2,airAmount:.15,reverbDecay:1.8,reverbDamping:.55,reverbPre:25,backend:'ASIO',sendEnabled:false,micVolume:.8,musicVolume:.5,masterVolume:.7,gate:true,compressor:true,eq:true,deesser:true,tune:false,reverb:true,autoKey:true,key:'C',tuneMode:'scale',tuneSpeed:35,tuneStrength:.8,gateDb:-50,compressorDb:-18,ratio:3,essAmount:.5,reverbWet:.18,shortEcho:false,longEcho:false,shortWet:.15,longWet:.18,shortMs:120,longMs:380,shortFeedback:.2,longFeedback:.4,autoAmount:.7,listenMode:'mix',eqGains:Array(13).fill(0)};
let live=false,recording=false,ready=false,busy=false,configured=false,portDriver='',autoRunning=false;
let telemetry={mic:0,music:0,master:0,waveform:Array(128).fill(0),micWave:Array(128).fill(0),musicWave:Array(128).fill(0)},previousErrors='';
const routingIds=['micChannel','musicLeft','musicRight','monitorLeft','monitorRight','sendLeft','sendRight'];
const logs=[];function log(message,error=false){logs.push(`${new Date().toLocaleTimeString()} ${error?'ERROR · ':''}${message}`);if(logs.length>200)logs.shift();$('log').textContent=logs.join('\n');$('log').scrollTop=$('log').scrollHeight;if(error)$('status').textContent=message;}
async function run(fn){if(busy){log('Chờ tác vụ audio hiện tại hoàn tất.');return null;}busy=true;try{return await fn();}catch(e){log(e.message,true);return null;}finally{busy=false;}}
function setText(el,value){const text=window.hnLocale.translate(value);if(el.textContent!==text)el.textContent=text;}
function command(op,data){return window.studio.command(op,data);}
async function params(change){settings={...settings,...await command('params',change)};renderSettings(false);}
function openDialog(id){const dialog=$(id);if(dialog){document.querySelector(`[data-restore="${id}"]`)?.remove();if(!dialog.open)dialog.show();dialog.style.zIndex=String(window.hnPanelZ=(window.hnPanelZ||100)+1);}}
function makeDialog(id,title){const dialog=document.createElement('dialog');dialog.id=id;dialog.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button data-close aria-label="Đóng">✕</button></div><div class="dialog-body"></div>`;document.querySelector('main').append(dialog);return dialog.querySelector('.dialog-body');}
function slider(container,title,id,min,max,step){const label=document.createElement('label');label.className='fader';const heading=document.createElement('div');heading.className='fader-heading';const text=document.createElement('span');text.textContent=title;const output=document.createElement('output');const input=document.createElement('input');input.type='range';Object.assign(input,{min,max,step});input.dataset.param=id;input.value=settings[id];output.textContent=input.value;input.addEventListener('input',()=>output.textContent=input.value);input.addEventListener('change',()=>run(()=>id==='autoAmount'?applyAmount(Number(input.value)):params({[id]:Number(input.value)})));heading.append(text,output);label.append(heading,input);container.append(label);}
async function applyAmount(value){settings={...settings,...await command('auto-amount',{autoAmount:value})};renderSettings(false);log('Mức Auto Vocal đã áp dụng cho mic');}
function fillSelect(id,list,indexed=false){const old=$(id).value;$(id).replaceChildren();list.forEach((name,i)=>{const option=document.createElement('option');option.value=indexed?i:name;option.textContent=indexed?`${i+1} · ${name}`:name;$(id).append(option);});if([...$(id).options].some(o=>o.value===old))$(id).value=old;}
function mode(){const asio=$('backend').value==='ASIO';$('asioRouting').hidden=!asio;for(const id of ['driver','ports','controlPanel'])$(id).hidden=!asio;for(const id of ['input','output'])$(id).disabled=asio||live||recording;setText($('routingNote'),asio?'Windows phát nhạc vào thiết bị ASIOVADPRO của ASIO Link Pro → MUSIC input. Mic → MIC input. Master → Monitor và Live send. Trong bảng routing của driver, tắt đường nhạc đi thẳng ra loa để tránh hai tiếng. Driver ASIO Link Pro x64 phải được cài trước.':'WASAPI loopback sao chép âm thanh Windows; nhạc vẫn phát trực tiếp từ hệ thống. Chọn output khác để tránh nghe hai lần.');setText($('micPort'),asio?$('micChannel').selectedOptions[0]?.textContent||'MIC input':$('input').value);setText($('musicFlow'),asio?'WINDOWS → ASIO LINK PRO → MUSIC INPUT → MUSIC VOLUME → MASTER':'WINDOWS → WASAPI LOOPBACK → MUSIC VOLUME → MASTER');}
async function readPorts(preserve=false){configured=false;const driver=$('driver').value;if(!driver)throw new Error('Chưa có driver ASIO x64. Cài ASIO Link Pro rồi Refresh.');const d=await command('ports',{driver});const same=preserve&&settings.driver===driver;const defaults={micChannel:['Input1',0],musicLeft:['LinkIn3',2],musicRight:['LinkIn4',3],monitorLeft:['Output1',0],monitorRight:['Output2',1],sendLeft:['LinkOut3',2],sendRight:['LinkOut4',3]};const norm=x=>x.toLowerCase().replace(/[^a-z0-9]/g,'');for(const id of routingIds){const list=id==='micChannel'||id.startsWith('music')?d.inputs:d.outputs;fillSelect(id,list,true);const [name,fallback]=defaults[id];const found=list.findIndex(x=>norm(x)===norm(name));const value=same&&settings[id]!==undefined?settings[id]:found>=0?found:fallback;$(id).value=String(value<list.length?value:0);}portDriver=driver;log(`ASIO ${driver}: ${d.inputs.length} inputs / ${d.outputs.length} outputs`);}
async function refresh(){configured=false;const d=await command('devices');fillSelect('input',d.inputs);fillSelect('output',d.outputs);fillSelect('driver',d.drivers||[]);if(settings.driver&&(d.drivers||[]).includes(settings.driver))$('driver').value=settings.driver;else{const link=(d.drivers||[]).find(x=>/asio.*link|link.*pro/i.test(x));if(link)$('driver').value=link;}mode();log(`Devices: ${d.inputs.length} input / ${d.outputs.length} output / ${(d.drivers||[]).length} ASIO`);if($('backend').value==='ASIO')await readPorts(true);}
function selected(){const c={backend:$('backend').value,input:$('input').value,output:$('output').value,driver:$('driver').value,sampleRate:Number($('sampleRate').value),bufferSize:Number($('bufferSize').value),sendEnabled:$('sendEnabled').checked};for(const id of routingIds)c[id]=Number($(id).value);return c;}
async function configure(){configured=false;if(live||recording)throw new Error('Tắt LIVE và REC trước khi đổi thiết bị.');if($('backend').value==='ASIO'){if(!$('driver').value)throw new Error('Chưa chọn driver ASIO x64.');if(portDriver!==$('driver').value)await readPorts(true);}else if(!$('output').value)throw new Error('Chưa chọn thiết bị output.');settings=await command('configure',{...settings,...selected()});configured=true;renderSettings();log(`Output: ${settings.output} · ${settings.sampleRate} Hz / ${settings.bufferSize} samples`);}

const fx=[['NOISE GATE','gate','Threshold dB','gateDb',-80,-10,1],['COMPRESSOR','compressor','Threshold dB','compressorDb',-50,0,1],['13-BAND EQ','eq'],['DE-ESSER','deesser','Sibilance reduction','essAmount',0,1,.01],['AUTO-TUNE','tune','Correction strength','tuneStrength',0,1,.01],['LỌC TRẦM','highpass','Tần số cắt (Hz)','highpassHz',40,250,1],['ẤM GIỌNG','warmth','Độ ấm','warmthAmount',0,1,.01],['SÁNG GIỌNG','air','Độ sáng','airAmount',0,1,.01],['REVERB','reverb','Wet / dry','reverbWet',0,1,.01],['SHORT ECHO','shortEcho','Echo amount','shortWet',0,.8,.01],['LONG ECHO','longEcho','Echo amount','longWet',0,.8,.01],['DELAY VST3','delay','Delay amount','delayWet',0,.8,.01]];
for(const [name,id,title,param,min,max,step]of fx){const card=document.createElement('article');card.className='effect';card.id=`fx-${id}`;card.innerHTML=`<h3>${name}</h3><p id="summary-${id}" class="fx-summary"></p><div><button class="toggle" data-toggle="${id}">OFF</button><button data-open="${id}Dialog">Chỉnh</button></div>`;$('effects').append(card);const body=makeDialog(`${id}Dialog`,`${name} · ${["reverb","shortEcho","longEcho","delay"].includes(id)?"SAU VST · CHỈ MIC":"MIC ONLY"}`);const toggle=document.createElement('button');toggle.dataset.toggle=id;toggle.className='toggle';body.append(toggle);if(param)slider(body,title,param,min,max,step);if(id==='reverb'){for(const [name,values]of [['LIVE tự nhiên',{reverbWet:.24,reverbDecay:1.6,reverbDamping:.62,reverbPre:25,shortEcho:true,shortWet:.12,shortMs:115,shortFeedback:.18,longEcho:false,delay:false}],['Ballad vang dài',{reverbWet:.32,reverbDecay:2.7,reverbDamping:.55,reverbPre:40,shortEcho:false,longEcho:false,delay:true,delayWet:.18,delayMs:420,delayFeedback:.35,delayDuck:.55,delaySync:false,delayPingPong:true}],['Giọng khô rõ',{reverbWet:.12,reverbDecay:.8,reverbDamping:.65,reverbPre:15,shortEcho:false,longEcho:false,delay:false}]]){const preset=document.createElement('button');preset.textContent=name;preset.onclick=()=>run(()=>params({reverb:true,...values}));body.append(preset);}slider(body,'Độ dài vang (giây)','reverbDecay',.25,5,.05);slider(body,'Làm mềm đuôi vang','reverbDamping',0,1,.01);slider(body,'Khoảng trước vang (ms)','reverbPre',0,120,1);slider(body,'Stereo width','reverbWidth',0,1.5,.01);}if(id==='delay'){slider(body,'Delay time (ms)','delayMs',60,1500,1);slider(body,'Feedback','delayFeedback',0,.8,.01);slider(body,'Ducking','delayDuck',0,1,.01);slider(body,'Echo softness','delayTone',0,1,.01);slider(body,'Tempo BPM','delayBpm',40,240,1);for(const id of ['delaySync','delayPingPong']){const t=document.createElement('button');t.dataset.toggle=id;t.className='toggle';body.append(t);}const select=document.createElement('select');select.id='delayDivision';for(const [value,name]of [[.25,'1/16'],[.5,'1/8'],[.75,'1/8 dotted'],[1,'1/4'],[1.5,'1/4 dotted'],[2,'1/2']]){const o=document.createElement('option');o.value=value;o.textContent=name;select.append(o);}select.onchange=()=>run(()=>params({delayDivision:Number(select.value)}));body.append(select);const p=document.createElement('p');p.className='note';p.textContent='Delay nằm sau chuỗi VST và vang mic. Ducking giảm tiếng lặp khi đang hát; ping-pong đưa tiếng lặp luân phiên trái/phải. Nhạc không đi qua Delay này.';body.append(p);}
if(id==='compressor')slider(body,'Ratio','ratio',1,12,.1);if(id==='shortEcho'||id==='longEcho'){const short=id==='shortEcho';slider(body,'Echo time (ms)',short?'shortMs':'longMs',short?60:250,short?300:900,1);slider(body,'Feedback',short?'shortFeedback':'longFeedback',0,.75,.01);}if(id==='eq'){const eq=document.createElement('div');eq.id='eq';eq.className='eq';body.parentElement.classList.add('wide');body.append(eq);}
 if(id==='tune'){const assist=document.createElement('button');assist.dataset.toggle='aiAssist';assist.className='toggle';body.append(assist);const aiNote=document.createElement('p');aiNote.className='note';aiNote.textContent='AI hỗ trợ: mạng neural chạy tại máy đánh giá độ tin cậy của nốt; chỉnh cao độ vẫn bằng DSP. Mô hình học từ âm tổng hợp, chưa được đánh giá trên tập giọng hát thực.';body.append(aiNote);const keyLabel=document.createElement('label');keyLabel.textContent='Key bài hát';const select=document.createElement('select');select.id='key';for(const root of ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'])for(const minor of [false,true]){const option=document.createElement('option');option.value=root+(minor?'m':'');option.textContent=root+(minor?' Minor':' Major');select.append(option);}select.onchange=()=>run(()=>params({key:select.value}));keyLabel.append(select);body.append(keyLabel);const modeLabel=document.createElement('label');modeLabel.textContent='Chế độ chỉnh phô';const mode=document.createElement('select');mode.id='tuneMode';for(const [value,text]of [['scale','Theo key / scale'],['chromatic','Chromatic · nốt gần nhất']]){const o=document.createElement('option');o.value=value;o.textContent=text;mode.append(o);}mode.onchange=()=>run(()=>params({tuneMode:mode.value}));modeLabel.append(mode);body.append(modeLabel);slider(body,'Retune speed (ms)','tuneSpeed',1,250,1);const auto=document.createElement('button');auto.dataset.toggle='autoKey';auto.className='toggle';body.append(auto);const reset=document.createElement('button');reset.id='redetectKey';reset.textContent='Detect key again';reset.onclick=()=>run(async()=>{settings={...settings,...await command('key-reset')};renderSettings(false);});body.append(reset);const detected=document.createElement('p');detected.id='detected';body.append(detected);const explanation=document.createElement('p');explanation.className='note';explanation.textContent='AutoTune ON chỉnh cao độ mic theo nốt mục tiêu. Tốc độ thấp cho hiệu ứng rõ; tốc độ cao giữ giọng tự nhiên hơn. Auto Key tự dò và áp dụng key từ giọng hát. Cần hát nhiều nốt; khi chưa đủ dữ liệu, chỉnh phô theo nốt gần nhất.';body.append(explanation);}
}
const masterBody=makeDialog('masterFxDialog','HN MASTER · MIC + NHẠC');const masterToggle=document.createElement('button');masterToggle.dataset.toggle='masterFx';masterToggle.className='toggle';masterBody.append(masterToggle);for(const [title,id,min,max,step]of [['Low dB','masterLow',-6,6,.1],['Mid dB','masterMid',-6,6,.1],['High dB','masterHigh',-6,6,.1],['Stereo width','masterWidth',0,1.5,.01],['Thick','masterThick',0,1,.01],['Glue','masterGlue',0,1,.01],['Loudness dB','masterLoud',0,12,.1]])slider(masterBody,title,id,min,max,step);const masterPreset=document.createElement('button');masterPreset.textContent='LIVE cân bằng';masterPreset.onclick=()=>run(()=>params({masterFx:true,masterLow:.5,masterMid:0,masterHigh:.8,masterWidth:1,masterThick:.12,masterGlue:.2,masterLoud:2}));masterBody.append(masterPreset);const masterNote=document.createElement('p');masterNote.className='note';masterNote.textContent='HN MASTER xử lý tổng mic và nhạc. Cân âm sắc, độ dày, stereo và độ lớn; limiter an toàn vẫn hoạt động khi HN MASTER tắt.';masterBody.append(masterNote);
for(const [i,hz]of [40,63,100,160,250,400,630,1000,1600,2500,4000,6300,10000].entries()){const band=document.createElement('label');band.className='band';band.style.setProperty('--band-hue',String(185+i*10));const light=document.createElement('div');light.className='eq-light';const energy=document.createElement('div');energy.className='band-energy';energy.id=`eq-energy-${i}`;light.append(energy);band.append(light);const output=document.createElement('output');output.id=`eq-value-${i}`;const input=document.createElement('input');Object.assign(input,{type:'range',min:-18,max:18,step:.5,value:0,id:`eq-${i}`});input.oninput=()=>{output.textContent=`${input.value} dB`;band.style.setProperty('--gain',`${(Number(input.value)+18)/36*100}%`);};input.onchange=()=>run(async()=>{const gains=[...settings.eqGains];gains[i]=Number(input.value);await params({eqGains:gains});});const text=document.createElement('span');text.textContent=hz>=1000?`${hz/1000}k`:hz;band.append(output,input,text);$('eq').append(band);}
for(const [name,id,container]of [['MIC VOLUME','micVolume','micVolumeBox'],['MUSIC VOLUME','musicVolume','musicVolumeBox'],['MASTER VOLUME','masterVolume','masterVolumeBox']])slider($(container),name,id,0,1.5,.01);
slider($('autoControls'),'Mức Auto Vocal tổng thể','autoAmount',0,1,.01);

function updateSlot(i,data){if(!data)return;const slot=$(`slot-${i}`);slot.querySelector('.slot-name').textContent=data.path?data.path.split(/[\\/]/).pop():'Empty · Load .vst3';slot.dataset.on=String(data.on);slot.dataset.bypass=String(data.bypass);slot.classList.toggle('on',!!data.path&&!!data.on&&!data.bypass);slot.querySelector('[data-action=on]').classList.toggle('on',!!data.path&&!!data.on);slot.querySelector('[data-action=bypass]').classList.toggle('on',!!data.bypass);const controls=$(`pluginParams${i}`);controls.replaceChildren();for(const [j,p]of (data.parameters||[]).entries()){const label=document.createElement('label');label.className='fader';const heading=document.createElement('div');heading.className='fader-heading';const name=document.createElement('span');name.textContent=p.name;const output=document.createElement('output');output.textContent=Number(p.value).toFixed(3);const input=document.createElement('input');Object.assign(input,{type:'range',min:0,max:1,step:.001,value:p.value});input.oninput=()=>output.textContent=Number(input.value).toFixed(3);input.onchange=()=>run(()=>window.studio.slot(i,'parameter',{parameter:j,value:Number(input.value)}));heading.append(name,output);label.append(heading,input);controls.append(label);}if(!(data.parameters||[]).length)controls.textContent='Chưa có plugin hoặc plugin không cung cấp thông số.';}
for(let i=0;i<4;i++){const slot=document.createElement('article');slot.className='slot';slot.id=`slot-${i}`;slot.dataset.on='true';slot.dataset.bypass='false';slot.innerHTML=`<span class="tag">MIC INSERT 0${i+1}</span><div class="slot-name">Empty · Load .vst3</div><div class="slot-buttons"><button data-action="load">Load</button><button data-action="on">ON/OFF</button><button data-action="bypass">Bypass</button><button data-action="remove">Remove</button><button data-open="pluginDialog${i}">Chỉnh</button></div>`;slot.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>run(async()=>{const action=button.dataset.action,value=action==='on'?slot.dataset.on!=='true':slot.dataset.bypass!=='true';const data=await window.studio.slot(i,action,value);updateSlot(i,data);if(data)log(`VST3 slot ${i+1}: ${action}`);}));$('slots').append(slot);const body=makeDialog(`pluginDialog${i}`,`VST3 SLOT ${i+1} · MIC ONLY`);const controls=document.createElement('div');controls.id=`pluginParams${i}`;controls.textContent='Load VST3 trước khi chỉnh.';body.append(controls);}

function renderSettings(includeRouting=true){document.querySelectorAll('[data-param]').forEach(input=>{input.value=settings[input.dataset.param];input.previousElementSibling.querySelector('output').textContent=input.value;});document.querySelectorAll('[data-toggle]').forEach(button=>{const id=button.dataset.toggle;button.classList.toggle('on',!!settings[id]);button.textContent=id==='delaySync'?`TEMPO SYNC ${settings[id]?'ON':'OFF'}`:id==='delayPingPong'?`PING-PONG ${settings[id]?'ON':'OFF'}`:id==='aiAssist'?`AI ${settings[id]?'ON':'OFF'}`:id==='autoKey'?`AUTO KEY ${settings[id]?'ON':'OFF'}`:settings[id]?'● ON':'○ OFF';$(`fx-${id}`)?.classList.toggle('on',!!settings[id]);});for(let i=0;i<13;i++){$(`eq-${i}`).value=settings.eqGains[i];$(`eq-value-${i}`).textContent=`${settings.eqGains[i]} dB`;$(`eq-${i}`).parentElement.style.setProperty('--gain',`${(settings.eqGains[i]+18)/36*100}%`);}$('key').value=settings.key;$('key').disabled=!!settings.autoKey;$('tuneMode').value=settings.tuneMode;$('delayDivision').value=settings.delayDivision;document.querySelector('[data-param=delayMs]').disabled=!!settings.delaySync;document.querySelector('[data-param=delayBpm]').disabled=!settings.delaySync;const summaries={delay:`${settings.delaySync?settings.delayBpm+" BPM":settings.delayMs+" ms"} · ${Math.round(settings.delayWet*100)}%`,highpass:`${settings.highpassHz} Hz`,warmth:`${Math.round(settings.warmthAmount*100)}%`,air:`${Math.round(settings.airAmount*100)}%`,gate:`${settings.gateDb} dB`,compressor:`${settings.compressorDb} dB · ${Number(settings.ratio).toFixed(1)}:1`,eq:'40 Hz — 10 kHz',deesser:`${Math.round(settings.essAmount*100)}% reduction`,tune:`${settings.autoKey?(telemetry.keyReady?settings.key:'AUTO'):settings.key} · ${settings.tuneSpeed} ms`,reverb:`${Math.round(settings.reverbWet*100)}% wet`,shortEcho:`${settings.shortMs} ms · ${Math.round(settings.shortWet*100)}%`,longEcho:`${settings.longMs} ms · ${Math.round(settings.longWet*100)}%`};for(const [id,text]of Object.entries(summaries))$(`summary-${id}`).textContent=text;document.querySelectorAll('[data-listen]').forEach(b=>b.classList.toggle('on',b.dataset.listen===settings.listenMode));if(includeRouting){for(const id of ['backend','driver',...routingIds,'input','output','sampleRate','bufferSize'])if(settings[id]!==undefined)$(id).value=settings[id];$('sendEnabled').checked=!!settings.sendEnabled;}mode();$('latency').textContent=`${settings.sampleRate||48000} Hz / ${settings.bufferSize||512} samples`;$('outputPort').textContent=settings.output||'Chưa Apply audio';$('sendStatus').textContent=settings.sendEnabled?'SECOND MASTER OUTPUT ON':'Second Master output OFF';$('autoControls').querySelector('input').disabled=!settings.autoProfile||autoRunning;}
function renderTransport(){$('live').classList.toggle('on',live);setText($('live'),live?'● LIVE ON':'● LIVE OFF');$('rec').classList.toggle('on',recording);setText($('rec'),recording?'■ STOP REC':'● REC WAV 24-bit');for(const id of ['backend','driver',...routingIds,'sendEnabled','ports','controlPanel','input','output','sampleRate','bufferSize','apply','refresh','load'])$(id).disabled=live||recording;mode();$('autoControls').querySelector('input').disabled=!settings.autoProfile||autoRunning;$('autoStart').disabled=!live||autoRunning;$('autoCancel').disabled=!autoRunning;}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.open)openDialog(b.dataset.open);if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.toggle)run(()=>params({[b.dataset.toggle]:!settings[b.dataset.toggle]}));if(b.dataset.listen)run(async()=>{await params({listenMode:b.dataset.listen});log(`Monitor nguồn: ${b.dataset.listen.toUpperCase()}`);});});
for(const id of ['backend','driver',...routingIds,'sendEnabled','input','output','sampleRate','bufferSize'])$(id).addEventListener('change',()=>{configured=false;mode();});
$('driver').addEventListener('change',()=>run(()=>readPorts(false)));$('backend').addEventListener('change',()=>{if($('backend').value==='ASIO'&&$('driver').value)run(()=>readPorts(true));});
$('ports').onclick=()=>run(()=>readPorts(true));$('controlPanel').onclick=()=>run(async()=>{if(!configured)await configure();const r=await command('control-panel');configured=false;log(r.opened?'Driver panel opened. Apply audio again after changing routing.':'Driver has no control panel.',!r.opened);});
$('refresh').onclick=()=>run(refresh);$('apply').onclick=()=>run(configure);$('test').onclick=()=>run(async()=>{if(!configured)await configure();const r=await command('test');log(`TEST 440 Hz → ${r.output} (2 giây)`);});
$('audioTest').onclick=$('test').onclick;
$('live').onclick=()=>run(async()=>{if(!ready)throw new Error('Native audio chưa sẵn sàng.');if(!configured)await configure();const r=await command('live',{on:!live});live=r.live;if(!live)autoRunning=false;renderTransport();$('status').textContent=live?'LIVE · MIC FX + MUSIC DRY':'Audio ready · LIVE OFF';log(live?`LIVE ON · ${r.source}`:'LIVE OFF');});
$('rec').onclick=()=>run(async()=>{if(!configured)await configure();const r=await window.studio.record(!recording);if(r){recording=r.recording;renderTransport();log(recording?'Recording Master WAV 24-bit':'WAV đã hoàn tất');}});
$('autoStart').onclick=()=>run(async()=>{const r=await command('auto-vocal');autoRunning=r.running;$('autoStatus').textContent='Hát rõ vào MIC trong 6 giây…';renderTransport();});$('autoCancel').onclick=()=>run(async()=>{await command('auto-vocal',{cancel:true});autoRunning=false;$('autoStatus').textContent='Đã hủy.';renderTransport();});
for(const action of ['save','load'])$(action).onclick=()=>run(async()=>{if(action==='save'&&!configured)await configure();const result=await window.studio.project(action);if(result){if(action==='load'){settings={...settings,...result,backend:result.backend||'Windows Audio',listenMode:'mix'};renderSettings();if(settings.backend==='ASIO')await readPorts(true);configured=true;await params({listenMode:'mix'});result.slots?.forEach((s,i)=>updateSlot(i,s));}log(`Project ${action} complete`);}});
$('exportLog').onclick=()=>run(()=>window.studio.exportLog());
window.studio.onEvent(data=>{if(data.event==='ready'){ready=true;$('status').textContent='Native audio ready · Audio Settings → Apply';log(data.backend);run(refresh);}else if(data.event==='log'){log(data.message);}else if(data.event==='error'){log(data.message,true);autoRunning=false;renderTransport();}else if(data.event==='auto-complete'){autoRunning=false;settings={...settings,...data.settings};renderSettings(false);renderTransport();$('autoStatus').textContent=data.message;log(data.message);}else if(data.event==='meters'){telemetry=data;autoRunning=data.autoRunning;renderTransport();$('autoProgress').value=data.autoProgress||0;if(autoRunning)$('autoStatus').textContent=`Đang đo MIC… ${Math.round((data.autoProgress||0)*100)}%`;const errors=`${data.loopbackError}/${data.captureDrops}/${data.recordDrops}/${data.underruns}`;if(errors!==previousErrors&&(data.loopbackError||data.captureDrops||data.recordDrops||data.underruns)){log(`Audio diagnostics: loopback error=${data.loopbackError}, capture drops=${data.captureDrops}, WAV drops=${data.recordDrops}, oversized blocks=${data.underruns}`,true);previousErrors=errors;}const names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];if(settings.autoKey&&data.keyReady){settings.key=names[data.detectedKey%12]+(data.detectedKey>=12?'m':'');$('key').value=settings.key;$('summary-tune').textContent=`AUTO · ${settings.key} · ${settings.tuneSpeed} ms`;}$('key').disabled=!!settings.autoKey;setText($('detected'),settings.autoKey?(data.keyReady?`AUTO KEY · ${settings.key} · ${Math.round((data.keyConfidence||0)*100)}%`:'Auto Key is listening · Sing several different notes'):'Auto Key OFF · Chọn key bài hát hoặc Chromatic');$('pitch').textContent=data.pitchHz?`${data.pitchHz.toFixed(1)} Hz`:'— Hz';setText($('target'),data.targetHz?`Target ${data.targetHz.toFixed(1)} Hz · ${Math.round((data.pitchConfidence||0)*100)}% confidence`:'Target —');}});
const canvas=$('wave'),ctx=canvas.getContext('2d'),waves=new Set(['micWave','musicWave','waveform']);document.querySelectorAll('[data-wave]').forEach(b=>b.onclick=()=>{const key=b.dataset.wave;if(waves.has(key))waves.delete(key);else waves.add(key);b.classList.toggle('on',waves.has(key));});
function draw(){const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#152337';ctx.lineWidth=1;for(let row=1;row<4;row++){ctx.beginPath();ctx.moveTo(0,row*h/4);ctx.lineTo(w,row*h/4);ctx.stroke();}for(let col=1;col<10;col++){ctx.beginPath();ctx.moveTo(col*w/10,0);ctx.lineTo(col*w/10,h);ctx.stroke();}for(const [key,color]of [['micWave','#20ddf5'],['musicWave','#bd70ff'],['waveform','#ffbb43']]){if(!waves.has(key))continue;ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=10;ctx.lineWidth=key==='waveform'?3:2;ctx.beginPath();(telemetry[key]||[]).forEach((v,i)=>{const x=i*w/127,y=h/2-Math.max(-1,Math.min(1,v))*h*.43;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}ctx.shadowBlur=0;for(const id of ['mic','music','master']){const value=telemetry[id]||0;$(`meter-${id}`).style.transform=`scaleX(${Math.min(1,value)})`;$(`db-${id}`).textContent=value>.00001?`${(20*Math.log10(value)).toFixed(1)} dB`:'−∞ dB';}for(let i=0;i<13;i++){const level=telemetry.eqLevels?.[i]||0;const height=level>.00001?Math.max(0,Math.min(1,(20*Math.log10(level)+60)/60)):0;$(`eq-energy-${i}`).style.transform=`scaleY(${height})`;$(`eq-energy-${i}`).style.opacity=String(.35+height*.65);}requestAnimationFrame(draw);}
$('language').value=window.hnLocale.language;$('applyLanguage').onclick=()=>{window.hnLocale.apply($('language').value);$('languageStatus').textContent='Language applied and saved.';renderSettings(false);renderTransport();};
renderSettings();renderTransport();draw();window.hnLocale.start();

document.getElementById('asioDownload').addEventListener('click',e=>{e.preventDefault();studio.downloadAsio().catch(error=>console.error(error));});

window.hnEnsureAudio=async()=>{if(!ready)throw new Error('Native audio chưa sẵn sàng');if(!configured)await configure();};

$('scanLiveVst').onclick=()=>run(async()=>{const result=await window.studio.timeline({action:'plugins'});fillSelect('livePluginLibrary',(result.plugins||[]).map(p=>p.name));const list=result.plugins||[];Array.from($('livePluginLibrary').options).forEach((o,i)=>o.value=list[i].path);const auto=list.find(p=>/auto.?tune/i.test(p.name));if(auto)$('livePluginLibrary').value=auto.path;$('livePluginHint').textContent=list.length?`${list.length} VST3`:'Chưa tìm thấy VST3. Cài plugin x64 dạng VST3 rồi quét lại.';});
$('loadLiveInstalled').onclick=()=>run(async()=>{if(!$('livePluginLibrary').value||!/.vst3$/i.test($('livePluginLibrary').value))throw new Error('Chọn VST3 đã cài trước');const i=Number($('livePluginSlot').value);updateSlot(i,await window.studio.slot(i,'installed',{path:$('livePluginLibrary').value}));});
