'use strict';
(() => {
 const $=id=>document.getElementById(id);const tr=s=>window.hnLocale.translate(s);let loading=false;
 function render(data){if(!data)return;data.names.forEach((name,i)=>{const b=document.querySelector(`[data-sfx="${i}"]`);if(b)b.textContent=tr(name);});$('sfxVolume').value=data.volume;}
 async function action(pad){if(loading)return;loading=true;try{await window.hnEnsureAudio();await window.studio.command('soundboard',{action:'trigger',pad});const b=document.querySelector(`[data-sfx="${pad}"]`);b?.classList.add('firing');setTimeout(()=>b?.classList.remove('firing'),650);}catch(e){$('status').textContent=e.message;}finally{loading=false;}}
 document.querySelectorAll('[data-sfx]').forEach(b=>b.onclick=()=>action(Number(b.dataset.sfx)));
 $('sfxStop').onclick=()=>window.studio.command('soundboard',{action:'stop'}).catch(e=>$('status').textContent=e.message);
 $('sfxVolume').onchange=()=>window.studio.command('soundboard',{action:'volume',volume:Number($('sfxVolume').value)}).catch(e=>$('status').textContent=e.message);
 $('sfxLoad').onclick=async()=>{try{render(await window.studio.loadSound(Number($('sfxPad').value)));}catch(e){$('status').textContent=e.message;}};
 // Floating, non-modal panels. Pointer capture keeps dragging out of the header reliable.
 window.hnPanelZ=window.hnPanelZ||100;const dock=document.createElement('div');dock.id='panelDock';document.body.append(dock);
 function wirePanel(panel){if(panel.dataset.floating)return;panel.dataset.floating='1';const head=panel.querySelector('.dialog-head');if(!head)return;const minimize=document.createElement('button');minimize.textContent='−';minimize.title='Thu nhỏ / Minimize';head.insertBefore(minimize,head.querySelector('[data-close]'));minimize.onclick=()=>{panel.close();const b=document.createElement('button');b.dataset.restore=panel.id;dock.querySelector(`[data-restore="${panel.id}"]`)?.remove();b.textContent=head.querySelector('h2').textContent;b.onclick=()=>{panel.show();panel.style.zIndex=++window.hnPanelZ;b.remove();};dock.append(b);};panel.addEventListener('pointerdown',()=>panel.style.zIndex=++window.hnPanelZ);head.addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.button!==0)return;const rect=panel.getBoundingClientRect(),dx=e.clientX-rect.left,dy=e.clientY-rect.top;panel.style.margin='0';panel.style.left=rect.left+'px';panel.style.top=rect.top+'px';head.setPointerCapture(e.pointerId);const move=v=>{panel.style.left=Math.max(0,Math.min(innerWidth-80,v.clientX-dx))+'px';panel.style.top=Math.max(0,Math.min(innerHeight-40,v.clientY-dy))+'px';};const stop=()=>{head.removeEventListener('pointermove',move);head.removeEventListener('pointerup',stop);head.removeEventListener('pointercancel',stop);};head.addEventListener('pointermove',move);head.addEventListener('pointerup',stop);head.addEventListener('pointercancel',stop);e.preventDefault();});}
 document.querySelectorAll('dialog').forEach(wirePanel);new MutationObserver(()=>document.querySelectorAll('dialog').forEach(wirePanel)).observe(document.querySelector('main'),{childList:true});
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 if(!reduced){const splash=document.createElement('div');splash.className='boot-splash';splash.innerHTML='<img src="assets/logo.webp" alt="HNStudio Musik AI"><span>LIVE · RECORD · CREATE</span>';document.body.append(splash);setTimeout(()=>{splash.classList.add('depart');setTimeout(()=>splash.remove(),350);},400);}
 document.addEventListener('click',e=>{if(reduced)return;const button=e.target.closest('button');if(!button||button.disabled)return;const wave=document.createElement('span');wave.className='click-ripple';const rect=button.getBoundingClientRect();wave.style.left=`${e.clientX?e.clientX-rect.left:rect.width/2}px`;wave.style.top=`${e.clientY?e.clientY-rect.top:rect.height/2}px`;button.append(wave);setTimeout(()=>wave.remove(),500);});
 window.studio.onEvent(data=>{if(data.event==='ready')window.studio.command('soundboard',{action:'state'}).then(render).catch(()=>{});});
})();
